xformers/components/__init__.py, xformers/components/residual.py, xformers/factory/block_factory.py
- Move the Pre/Post residual paths to the components, so that a full transformer can be built from /components alone
- makes it possible to submit a fused version in the future, with Triton
=> [refactor][Minor] Moving the residual path to the components

HOWTO.md, README.md, docs/source/custom_parts/index.rst, docs/source/index.rst, docs/source/triton/index.rst, xformers/components/residual.py, xformers/factory/block_factory.py, xformers/triton/k_layer_norm.py, xformers/triton/layer_norm.py
- Expanding the HTML doc a fair bit
- Adding a blocksparse code snippet
- Adding better credits
-  [x] Did you have fun?
=> [docs] Adding some new content, better credits, missing authors

xformers/components/attention/blocksparse.py
Move the blocksparse mask to half, same as the rest.
Not visible before because this test was not run on CI, the other PR enabling Triton on circle CI landed in between and rightly exposed it
=> [hotfix] Blocksparse mask moved to half

tests/test_triton_dropout.py, xformers/triton/dropout.py, xformers/triton/k_dropout.py
Fixes #56, could be that the unit test was a little strict (check that the tensor is the same when the dropout probability is 0. An example of a faulty run is [there](https://app.circleci.com/pipelines/github/facebookresearch/xformers/212/workflows/8988c71c-84f5-4bd0-bd59-ac7d293c2370/jobs/398/tests#failed-test-1), not obvious where the difference is, I've added a printout for hypothetical future issues
=> [nit][dropbox] Add a no-op codepath for p=0

.circleci/config.yml
Fixes https://github.blog/2021-09-01-improving-git-protocol-security-github/, git:// is not supported anymore
cc @anj-s @min-xu-ai, probably the same needs to be done on the fairscale side
=> [CI] tentative fix, git:// not supported anymore

xformers/components/attention/core.py, xformers/components/attention/scaled_dot_product.py
When using the block factory, this flag was not being passed, because this attention was not declared as depending on it..
- respect the causal flag
- handle bool and float masks (supposed additive)
=> [Fix] the causal handling for SDP

requirements-test.txt, stubs/torch/__init__.pyi, stubs/torch_stub_tests.py, xformers/components/positional_embedding/__init__.py, xformers/components/positional_embedding/sine.py
The main changes are:
+ Make the class generic in a variable `DimModel` and set the type of
`self.dim_model` as `DimModel`. That way, when it is initialized with
`self.dim_model`, Pyre will store the type. We have to add
`Generic[DimModel]` in this class because `self.dim_model` is defined in
this class.
+ Annotate `forward` as accepting a Tensor of shape N x N and returning
a Tensor of shape N x N x DimModel.
This is about as straightforward as it gets for shape types. There were no
major complications in this class. If even this is too cumbersome or hard to
follow, it will not get easier in other classes :) So, feedback welcome on the
understandability.
Note:
+ I added `from __future__ import annotations` so that the type
annotations are not evaluated at runtime. This is necessary …
=> [feat] Add shape types to sine.py.

tests/test_attentions.py, xformers/components/attention/core.py, xformers/components/attention/favor.py
If an attention was declared causal, then a mask is saved whose size is based on the expected max sequence length. This is then not updated at forward time, so it can happen that the mask overshoots the attention matrix
=> [bugfix] Small fix in case the sequence is smaller than the saved mask

.gitignore, CHANGELOG.md, examples/microGPT.py, tests/test_core_attention.py, xformers/components/attention/_sputnik_sparse.py, xformers/components/attention/core.py, xformers/components/attention/nystrom.py, xformers/components/attention/scaled_dot_product.py, xformers/components/attention/utils.py
- Fixes https://github.com/facebookresearch/xformers/issues/74, microGPT and causal attention work properly with Nystrom
- Fix attention masks being bool or additive (not all the codepaths probably, but at least the ones that Nystrom touched)
- Fix the small-sequence handling for sparse masks, this was broken prior to this PR and probably explains the hanging CI yesterday
=> [fix] Nystrom + microGPT + some additive masking

docs/source/conf.py, xformers/__init__.py
Moves current main to v0.0.4, so that we can make a difference in between `pip install xformers` and `pip install -e .`
=> [minor] bump v number for current main

xformers/components/attention/blocksparse.py
Update blocksparse to use additive attention, this would be more consistent with the core attention masking, which is now only additive or boolean. Perhaps we can allow either options to be specified?
=> update blocksparse to use additive attention, more consistent with core

.circleci/config.yml, packaging/build_wheel.sh, packaging/pkg_helpers.bash, requirements.txt, setup.py
This PR sets up CircleCI jobs that automatically build wheels for xformers, for different Python versions.
In order to kick the builds, the following is needed:
- create a branch named `release/v0.0.2`  (one can change the release version)
- apply needed modifications for the release (if needed)
- create a pull request (which don't need to be merged)
The pull request will launch the build jobs, together with a set of jobs to validate that the extensions have been properly built and can be loaded.
~In order to test this PR, I've temporarily changed the name of the branch to be `binaries_job` (the name of this branch), but last commits in this PR changes it to the corresponding regex for `release/...`~
EDIT: in order to facilitate testing / reviewing, I propose to for now merge this PR with …
=> Automate binary releases

examples/microViT.py, xformers/components/residual.py
Enables FusedLayerNorm by default in the factory (if triton is available and the gpu is compatible), brings a little more speed and same accuracy in the microViT dummy test.
Somewhat related to https://github.com/facebookresearch/xformers/issues/76
=> [Minor] FusedLayerNorm enabled by default in the factory

xformers/triton/layer_norm.py
Catch a case where the Triton install is broken (because the cuda install is broken), fallback to pytorch
Been told from @SeanNaren that this was useful (we already do this for the fused softmax)
=> [minor] softfail if the triton installation is broken

examples/microGPT.py, xformers/components/attention/favor.py, xformers/components/residual.py
Fixes #96
There was no bug per say, the Softmax approximation for Favor just requires a big dynamic range and the attention computation would overflow in fp16. I tested a couple of takes (limit the values a posteriori, catch inf etc..) but this would be ugly and break the backward graph, in the end keeping this nugget of computations in fp32 is the safest bet I think. Note that we only promote fp16 tensors, not bfloat16 for instance
=> [bugfix] Favor + fp16

tests/test_attention_utils.py, xformers/components/attention/utils.py
Merge masks should return shape that is expected for attn mask.
=> merge masks should return shape of attn mask

.circleci/config.yml
Fixes CI, was dying on the clang-format binary pulled in, dynamically linked with libbtsomething5 which was not available anymore. Just pull it from ubuntu, and move this step to the dependency installation (which is cached) 
=> [CI] Fix clang-format

examples/microGPT.py, tests/test_attentions.py, tests/test_favor.py, tests/test_nystrom_attention.py, xformers/components/attention/base.py, xformers/components/attention/core.py, xformers/components/attention/favor.py, xformers/components/attention/nystrom.py, xformers/components/attention/scaled_dot_product.py
- Fixes #103
- Adding a unit test checking that causality is correct for scaled dot product and FAVOR. Nystrom does not seem to pass that
- Fixes Favor not picking up the causal flag
- Fixes Favor causal not being trainable (but introduces a big memory use)
=> [bugfix] Causal mask being skipped if no extra mask

docs/source/conf.py, tests/test_attention_mask.py, tests/test_custom_ops.py, tests/test_pytorch_transformer_parity.py, tests/test_triton_fused_linear.py, xformers/__init__.py, xformers/components/__init__.py, xformers/components/attention/__init__.py, xformers/components/attention/attention_mask.py, xformers/components/attention/base.py, xformers/components/attention/core.py, xformers/components/attention/global_tokens.py, xformers/components/attention/random.py, xformers/components/attention/scaled_dot_product.py
- add a dedicated class to handle additive attention masks, and centralize some of the typical operations (change types, add to another mask, handle smaller sequences..)
- the sparse machinery is still the same and bools (cc @fmassa), I did not touch that. 
- I think that the above needs to be changed eventually, so that we converge towards additive masks all around, but it means that on the sparse side we need to completely handle a float additive mask, in that a value `a` would both mark the fact that this needs to be computed, and be added a posteriori to the computed attention value (not done right now)
- Fix https://github.com/facebookresearch/xformers/issues/90 (do not slice the attention mask)
- Fix https://github.com/facebookresearch/xformers/issues/91 (no causal flag in the core …
=> [partial refactor] Dedicated attention mask wrapper

xformers/benchmarks/benchmark_vit_timm.py
Closes https://github.com/facebookresearch/xformers/issues/108
Gives a way to compare end to end with an optimized PyTorch implementation
Interesting takeaways already
=> [tooling] Vit comparison bench

CHANGELOG.md, tests/test_attentions.py, xformers/components/attention/blocksparse.py, xformers/components/attention/core.py, xformers/components/attention/fourier_mix.py, xformers/components/attention/global_tokens.py, xformers/components/attention/lambda_layer.py, xformers/components/attention/linformer.py, xformers/components/attention/scaled_dot_product.py
Fixes #122 + adds a unit test to catch faulty dropouts
@fmassa is rewriting some of that part, but in the meantime `main` should not be knowingly broken
=> [Fix] attn_dropout

tests/test_attentions.py
Added a unit test in tests_attentions.py for testing torch script ability of attentions. Note that, in the unit test I am using tracing , but the better approach would be torch scripting given that there are some control flows (i.e., if then) in the implementations, however, currently torch script does not support some functionalities such as having variable number of arguments (i.e, *args, **kwargs). 
CircleCI passes the unit tests.
=> Add torch tracing unit test in test_attentions

xformers/triton/softmax.py
fallback to torch.log_softmax when tritron's sfotmax w/ log=True.
=> [fix] fall back to torch.log_softmax properly

README.md, tests/test_attentions.py, tests/test_block_factory.py, tests/test_rotary_embeddings.py, xformers/components/attention/base.py, xformers/components/attention/blocksparse.py, xformers/components/attention/global_tokens.py, xformers/components/attention/lambda_layer.py, xformers/components/attention/linformer.py, xformers/components/attention/local.py, xformers/components/attention/random.py, xformers/components/multi_head_dispatch.py, xformers/components/positional_embedding/rotary.py
=> [helpers] Better handling of  different sequence dimensions

docs/source/tutorials/pytorch_encoder.rst
Fixes links to use rst instead of markdown
=> Fix links, formatting broken

tests/test_triton_dropout.py
Fixes flaky dropout prob test, pull more samples
=> [hotfix] dropout test tolerance

docs/requirements.txt, xformers/factory/model_factory.py
The doc build and deployment was broken, [see](https://github.com/facebookresearch/xformers/runs/4742115586?check_suite_focus=true) and  the [current API description](https://facebookresearch.github.io/xformers/components/attentions.html). This came from the pyre-extensions not being present in the doc requirements, meaning that sphinx would die on this import and skip all the codebase
=> [doc][Minor] Fix empty html docs, choking on the pyre extensions

tests/test_reversible.py, xformers/components/reversible.py
Super minor, but should improve the code coverage for the reversible layers. Mark backwards as `# pragma: no cover`, and make sure to test training in the encoder and encoder+decoder case
=> [minor] Improving code coverage for the reversible layers

CHANGELOG.md, tests/test_favor.py, xformers/components/attention/favor.py
Thanks @fmassa for the heads up !
=> [bugfix][Favor] Same feature map for q and k

CHANGELOG.md, codecov.yml
Follow up from #189, I forgot to update the changelog, and updating codecov so that /experimental is not counted (there are tests, but need triton v2 and build from source for now
=> [minor] Changelog + codecov

CHANGELOG.md, README.md, experimental/ragged_inference/test_utils.py, requirements-test.txt, tests/test_block_factory.py, tests/test_feedforward.py, tests/test_model_factory.py, xformers/components/feedforward/fused_mlp.py, xformers/components/feedforward/mixture_of_experts.py, xformers/helpers/test_utils.py
Implements Mixture of Experts as a simple Feedforward option. Uses the great MoE implementation from [FairScale](https://github.com/facebookresearch/fairscale/), implemented by @msbaines back in the days
This is really for fun and completeness' sake. Example usecase: [Sparse ViT](https://ai.googleblog.com/2022/01/scaling-vision-with-sparse-mixture-of.html)
TODO:
=> [feat] Mixture of Experts

README.md
- remove the ´models' description, not valid anymore
- add the triton parts to the tree
- add the fused dropout(activation(x+bias))
=> [minor] Tentative README improvements

xformers/components/positional_embedding/sine.py
The downstream library has an older version of `pyre_extensions` and it
will take some time to release a new version. So, remove the use of
`pyre_extensions.Generic` in sine.py for now.
This unblocks moving the other commits downstream.
cc @dianaml0
=> [fix] Disable shape types in sine.py

xformers/sparse/utils.py
PyTorch now supports stable sort, so we can remove our past workaround that manually implemented stable sort.
On some quick benchmarks, this improves the `_transpose` speed by ~30%.
Tests are already implemented in https://github.com/facebookresearch/xformers/blob/d4b5757fe5a160fb016fb02eb4e74c2dcf75a75b/tests/test_custom_ops.py#L384-L397
=> Optimize sparse transpose

tests/test_pickling.py, xformers/components/attention/blocksparse.py, xformers/components/feedforward/mixture_of_experts.py, xformers/components/in_proj_container.py
Touches #203, but not for all configurations for now
=> [Partial Fix] Model pickability

tests/test_sparse_tensors.py, xformers/sparse/__init__.py, xformers/sparse/blocksparse_tensor.py
This PR creates a BlockSparse Tensor (similar to SparseCSRTensor). This will ultimately enable to use the same code-path in the `scaled_dot_product_attention`, so that users just need to pass a block-sparse matrix in the mask to get the expected results (as is the case now with `SparseCSRTensor`). This is not yet entirely plugged, but will be done in a follow-up PR.
I haven't made the `Blocksparse` `nn.Module` use our new Tensor for now as it relies on additional information for the softmax which I would rather not add in the `BlockSparseTensor` API (all the different types of masking).
Note that for now the backward of `masked_matmul` is not passing, which is very weird as it was pretty-much a copy-paste of what we had before. This needs to be further investigated.
=> Create BlockSparse Tensor

CHANGELOG.md, tests/test_triton_blocksparse.py, xformers/components/attention/blocksparse.py
Fixes #206, constraints the block sizes to being the ones we actually uni tests. Other sizes probably work but bring no benefit really, since you can express the pattern with the smaller blocks
=> [fix] blocksparse sanity checks 

xformers/sparse/__init__.py
Tests fail if Triton is not available when using Blocksparse Tensor
=> [fix] catch error importing blocksparse tensor when triton not installed

tests/test_sparse_tensors.py, xformers/sparse/__init__.py, xformers/sparse/blocksparse_tensor.py
This is a follow-up from https://github.com/facebookresearch/xformers/pull/213
Now that we have fall-back implementations, we don't need to error-out if Triton is not available in the system.
We still raise the warning as before, but at least users can use the CPU / naive CUDA implementations.
=> Make triton optional in BlockSparseTensor

tests/test_reversible.py
CircleCI reported that the reversible unit test was taking north of a minute on CPU ([see](https://app.circleci.com/insights/github/facebookresearch/xformers/workflows/build/tests?branch=main)), simplifying it. Should also help with FB infra
cc @dianaml0 
Insta land, hoping that's ok (cc @fmassa  )
=> [CI][minor] Another very minor change, speed up the cpu runs

CHANGELOG.md, tests/test_triton_layernorm.py, xformers/triton/layer_norm.py
Follow up from #219, may not explain but better to stick to the same values all around 
=> [Minor] Align layer norm eps value to PyTorch

CHANGELOG.md, examples/microViT.py, tests/test_triton_layernorm.py, xformers/components/feedforward/fused_mlp.py, xformers/components/feedforward/mlp.py, xformers/triton/layer_norm.py
Looking into #219 exposed that  MLP and FusedMLP were not using the same defaults (bias and no bias respectively), and that Timm defaulted to using a bias. This PR 
- exposes the bias flag
- uses the same default for both MLP and FusedMLP
- use default bias=True so that it's the same as Timm
=> [Minor] Expose bias options for both MLP and FusedMLP, use same defaults

xformers/components/attention/random.py
* Fix typo in attention.random doc. Remove extra "means".
* Unify style for the BigBird reference with what is done [here](https://github.com/facebookresearch/xformers/blob/a65c2432efac89e62257c7ef47aeae1c93ab8f27/xformers/components/attention/local.py#L60).
Thanks for the great repo.
=> Fix typo in attention.random doc

xformers/triton/dropout.py, xformers/triton/fused_linear_layer.py, xformers/triton/k_layer_norm.py, xformers/triton/layer_norm.py, xformers/triton/softmax.py
Remove non-kernel code from k_layer_norm basically, do the same as the other triton layers. No logic or perf change, just moving the code around
Initially spotted when looking into #219, but ended up not fixing anything
=> [Minor] Small triton layer norm refactor, align the different triton layers

xformers/factory/model_factory.py
I don't think that fixes #219, but related (init not properly done). Caught when implementing #227, I think that we would need to add a proper explicit/programable init to the  model factory to rule out any issue there. 
In the meantime this must have been a typo, I'm not sure when it slipped in but does not make a lot of sense (biases are typically zero-init but linear weights are one-init for instance, this line would nuke that). This PR makes sure that by default the init values defined by the components are preserved
cc @jramapuram
=> [hotfix] Init typo 

xformers/components/multi_head_dispatch.py
Rewriting some of the projection operations in the MHA, I stumbled upon this, which nukes the self-attention optimization and is generally a small speed loss (happens all the time, even if not needed because all the tensors are the same).
Does not change any of the logic
=> [hotfix][minor] Speed fix MHA / self attention

CHANGELOG.md, tests/test_residual.py, xformers/components/__init__.py, xformers/components/residual.py, xformers/components/reversible.py, xformers/factory/block_factory.py
Could well explain #219 (cc @jramapuram), I stumbled upon this bug by luck while rewriting some of the input projection part and being more strict with self-attention (in that case the tensors need to be the exact same objects, with an incoming PR, makes it easier to catch a bug if the intent is self attention). 
This showed that the pre-norm wrapper was (a) only normalizing the first input (b) creating new objects because it would normalize the tensors one by one, even if it was the same tensor to begin with. This is a bug which already existed in the past and was fixed, not sure how it came back (long lived branch + botched merge maybe), hence the unit test and the change of interface to make sure that this does not happen anymore. Consequence was both correctness + speed (after the …
=> [bug] Pre-norm wrapper only normalizing the first input

CHANGELOG.md, README.md, examples/microGPT.py, examples/microViT.py, tests/test_model_factory.py, tests/test_pytorch_transformer_parity.py, xformers/components/residual.py, xformers/factory/block_factory.py, xformers/factory/model_factory.py
- Implements [DeepNorm](https://arxiv.org/abs/2203.00555v1) (aka DeepNet paper, 1000 layers Transformer) support, as a "layer norm style" config flag
- cleans up the full model weight init
Open question : should we support something else than xavier init for the weights in the full model case ?
TODO
=> [feat] DeepNorm/DeepNet support (#227)

MANIFEST.in
Gets rid of warning:
`warning: manifest_maker: MANIFEST.in, line 4: 'recursive-include' expects <dir> <pattern1> <pattern2> ...`
=> Fix warning in MANIFEST.in

tests/test_attention_patterns.py, tests/test_attentions.py, tests/test_block_factory.py, tests/test_compositional_attention.py, tests/test_core_attention.py, tests/test_global_attention.py, tests/test_model_factory.py, tests/test_nystrom_attention.py
Decreased CPU test suite runtime in Meta internal testing utility. This was requested via a Meta task filed by @dianaml0.
The changes include:
- decreasing the number of parameterized test cases in some of the highest cardinality test cases
- reducing tensor sizes in some of the slowest running tests (several minute runtime in Sandcastle -> few seconds)
- small number of changes to reduce inefficiencies in the code involving itertools.product()
- [🙃 ] Did you have fun?
- [-] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
This was requested via a Meta task.
- [-] Did you make sure to update the docs?
- [-] Did you write any new necessary tests?
- [-] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? …
=> T112038261 reduce test runtime

CHANGELOG.md, xformers/components/attention/attention_mask.py
Fixes #246
- [🙃] Did you have fun?
- [o] Did you make sure to update the docs?
- [o] Did you write any new necessary tests?
- there are tests existing for torchscript, but not on the whole model. Some parts will not work for sure (triton for instance).
=> [fix] Torchscriptability FTW

.circleci/config.yml, requirements-test.txt, xformers/benchmarks/benchmark_vit_timm.py
The CI agents that we use have cuda 11.2, but we were pulling in the 11.1 builds. Somehow it worked before, but stopped working recently (CI still works because this step is usually cached). Agents are available for cuda 11.1, aligning the two with this PR
=> [CI][Super minor] Align nightly pre-builts and agents' cuda

CHANGELOG.md, HOWTO.md, README.md, examples/microViT.py, tests/test_block_factory.py, xformers/components/simplicial_embedding.py, xformers/factory/block_factory.py
Follow up to #259, adds simplicial embeddings + option to add it at the bottom of an encoder. I actually don't believe that it's super important (it was kind of easy to add manually beforehand), but it does not take much space (orthogonal to the rest), and I would be curious to see how that affects things like openclip and friends.
I've done a dummy test on the ViT Cifar training, it does not meaningfully affects the score (in either way), which is not too surprising (the linear probe afterwards could already recover from "misaligned" dimensions given the strong supervised signal, which is what simplicial embeddings could improve)
If we didn't discuss your PR in Github issues …
=> [feat][minor] Simplicial embeddings

tests/test_mem_eff_attention.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cpu/attention.cpp, xformers/components/attention/csrc/cuda/attention.cu, xformers/ops.py
This PR implements the memory-efficient attention mechanism from https://arxiv.org/pdf/2112.05682v2.pdf, with both CPU and CUDA kernels. For now, only fp32 is supported.
The CPU implementation is fairly naive and I haven't focused on optimizing it (yet). So you should expect it to be quite a bit slower than a baseline CPU implementation in PyTorch. But it is generic and should support all cases
For the CUDA implementation, the performance is quite competitive with a baseline pytorch implementation for fp32 in terms of runtime (within 10% for most cases), while the memory savings are quite significant (10x+).
Here are some numbers (run on a P100 GPU):
<details>
<summary>
Speed / memory improvements on the CUDA case
</summary>
```
Optimized Memory used: 0.0634765625 MB
Vanilla Memory used: …
```
=> Memory-efficient attention - forward pass

HOWTO.md, xformers/benchmarks/benchmark_multi_head_dispatch.py, xformers/benchmarks/benchmark_revnet.py
Benchmarks xFormers MultiHeadDispatch again Pytorch's version.
=> [feat] Multihead dispatch benchmark

CHANGELOG.md, xformers/components/multi_head_dispatch.py
improvement for #264, but does not fix all the points. Divisibility by the number of heads is what we want to check here, really
=> [fix] Q/K/V needs to be divisible by heads, not more

examples/microGPT.py, stubs/torch/fft/__init__.pyi, stubs/torch/linalg/__init__.pyi, stubs/torch/nn/functional.pyi, stubs/torch/nn/functional/__init__.pyi, stubs/torch/sparse/__init__.pyi, stubs/torch_stub_tests.py, tests/test_triton_blocksparse.py, tests/test_triton_fused_linear.py, xformers/benchmarks/LRA/run_tasks.py, xformers/benchmarks/benchmark_encoder.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/benchmarks/benchmark_nystrom_utils.py, xformers/benchmarks/benchmark_pytorch_transformer.py, xformers/benchmarks/utils.py, xformers/components/attention/attention_patterns.py, xformers/components/attention/blocksparse.py, xformers/components/attention/compositional.py, xformers/components/residual.py, xformers/utils.py
Minor blocksparse refactoring, update block size restrictions, relax power of two constraint.
- [ X] Did you have fun?
- [ X] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [ X] Did you write any new necessary tests?
=> Minor blocksparse refactoring, update block size restrictions, relax power of two constraint

tests/test_block_factory.py, tests/test_model_factory.py, xformers/components/attention/base.py, xformers/components/attention/blocksparse.py, xformers/components/attention/compositional.py, xformers/components/attention/favor.py, xformers/components/attention/fourier_mix.py, xformers/components/attention/global_tokens.py, xformers/components/attention/lambda_layer.py, xformers/components/attention/linformer.py, xformers/components/attention/local.py, xformers/components/attention/nystrom.py, xformers/components/attention/ortho.py, xformers/components/attention/random.py, xformers/components/attention/scaled_dot_product.py, xformers/components/multi_head_dispatch.py
Preamble to the Triton2 PR (since triton 2 will change the blocksparse attention and not support attention masks anymore)
The unit test which now fails on CI should be unrelated to this PR, and is fixed by the next PR in line, triton2
=> [feat][minor] 2/3 Make it explicit whether an attention mechanism supports a mask

docs/source/conf.py, xformers/__init__.py
Discussed on the Triton2 PR, move the python package numbering to 'next.dev' to make it easier to differentiate in between the current main package and the pip version
=> [minor] Adding dev version numbering' 

xformers/components/multi_head_dispatch.py
As discussed with Ben offline, when using forward module hooks on the attention block arguments need to be passed in as positional args to access them within the hook (can be seen in the [docs](https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html#torch.nn.modules.module.register_module_forward_hook)).
My use case for this is profiling using the [DeepSpeedProfiler](https://www.deepspeed.ai/tutorials/flops-profiler/). The profiler attaches hooks to modules to calculate how many FLOPs are done. When using xformers we need to declare a few more hooks in order to calculate them correctly, (as seen [here](https://github.com/SeanNaren/SmallScience/blob/feat/profiling/profiler.py#L26)).
An example!
```python
import torch
from …
```
=> Remove keyword arguments to attention call, pass as positional

.circleci/config.yml
Minor, properly cache the env in between jobs, speeding up CI  a little.
I compared that with not using a cache at all, using a cache is actually faster:
- [with a warm cache](https://app.circleci.com/pipelines/github/facebookresearch/xformers/1460/workflows/1329534e-e14d-40b5-9775-daebde1adf4d) ~26 minutes
- [prior to this PR](https://app.circleci.com/pipelines/github/facebookresearch/xformers/1458/workflows/6ebb619b-296f-4c23-a705-30d748c0324c) ~35 minutes
- [no cache](https://app.circleci.com/pipelines/github/facebookresearch/xformers/1456/workflows/15e2decc-ade0-43a2-9f21-dce3a4cc5585) ~32 minutes 
(timings give or take a couple of minutes, but a proper cache is clearly better)
Anyone in the community is free to review the PR once the tests have …
=> [CI] Fix caching the env in between jobs

tests/test_mem_eff_attention.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cpu/attention.cpp, xformers/components/attention/csrc/cuda/attention.cu, xformers/ops.py
This PR implements the memory-efficient attention mechanism from https://arxiv.org/pdf/2112.05682v2.pdf, with both CPU and CUDA kernels, targetting the backward implementation. For now, only fp32 is supported.
The CPU implementation is naive and not meant to be fast, and is there only as a reference.
The CUDA implementation has competitive runtimes compared to a vanilla PyTorch implementation, while using 10x+ less memory. 
Contrary to the forward implementation, the backwards supports inputs of arbitrary number of embedding sizes. I'll probably update the forward implementation to use a similar approach in the future.
In order to keep the backwards somewhat efficient, we need to return the `logsumexp` during forward as well. For some reason, I needed to template it in CUDA otherwise I …
=> Memory efficient attention - backward pass

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/attention.cu
Fixes cases where we do `attention().sum().backward()`, which has a non-contiguous `grad_out`
=> Handle non-contiguous grad_out and add checks for qkv

CHANGELOG.md, examples/microViT.py, tests/test_model_factory.py, xformers/components/residual.py, xformers/factory/model_factory.py
Hotfix an init of the projection matrix for the value being skipped when using deepnorm and self attention. See bottom of #219 for context.
TODO:
=> [fix] Deepnorm self-attention value proj init scaling missing

examples/microViT.py, tests/test_embedding.py, xformers/components/__init__.py, xformers/components/patch_embedding.py, xformers/components/positional_embedding/param.py, xformers/factory/block_configs.py, xformers/factory/block_factory.py, xformers/factory/model_factory.py
- First step to close #285, we actually need to support the patch embedding part to be able to generate all [Metaformers](https://arxiv.org/pdf/2111.11418.pdf). We could expose more options as of what function is used to "pool" the patches, this PR follows ViT in that it's a Conv2d
- Add a learnable position embedding, somehow not there
- Change the microViT example so that it benefits from this new support
- Testing a "classic" small ViT training on CIFAR, seems alright
TODO:
=> [feat] Natively support PatchEmbedding layers

xformers/components/attention/global_tokens.py
`scaled_dot_product_attention` already handles dropout internally.
In
https://github.com/facebookresearch/xformers/blob/8a0507086e5fca99da752258b3c2b56b233ceaa4/xformers/components/attention/global_tokens.py#L119
we are applying dropout in the output of the attention block, which is not intended.
This PR fixes it by removing the extra dropout
=> Remove double dropout in global attention

requirements-test.txt, xformers/triton/k_fused_matmul_bw.py
worked on my machine.. (tm). Looks like the initial JIt or micro benchs are too slow for our CI, reverting to an older version which works. 
=> [hotfix] looks like triton matmul op is initially too slow for CI

requirements-test.txt
Fixes broken dependencies that protobuf 4.20 caused
=> [CI] Lock protobuf to 3.20.1

CHANGELOG.md, xformers/benchmarks/benchmark_mlp.py, xformers/components/feedforward/fused_mlp.py
Fixes the FusedMLP block having twice the bias layers, found randomly when working on the weight inits (#312)
=> [hotfix] doubled bias in FusedMLP

CHANGELOG.md, tests/test_rotary_embeddings.py, xformers/components/positional_embedding/rotary.py
Fixes #325 I hope + extending the unit test
=> [fix] Rotary embeddings respecting input types

CHANGELOG.md, README.md, examples/cifarMetaformer.py, tests/test_block_factory.py, tests/test_feedforward.py, tests/test_model_factory.py, xformers/components/feedforward/base.py, xformers/components/feedforward/conv_mlp.py, xformers/factory/block_factory.py, xformers/factory/weight_init.py, xformers/helpers/hierarchical_configs.py
One step towards #319, adding the MLP/Conv2d hybrid proposed by the [VAN paper](https://arxiv.org/pdf/2202.09741.pdf). Interestingly, testing this with a "Metaformer" (in true xformers fashion you can mix and match) on a tiny example does bring a measurable benefit.
<details>
<summary>Small (6M) Metaformer on Cifar10</summary>
Orange is the default (scaled dot product attention, not poolformer) + MLP
White is the same but with the ConvMLP that this PR introduces
</details>
=> [feat] Adding a conv MLP, following VAN

HOWTO.md, docs/source/tutorials/sparse_vit.rst, tests/test_timm_sparse.py
Fixes documentation to reflect correct revised class name "TimmSparseAttention" instead of "TimmAttentionWrapper"
Changes test file name and method name to reflect same
=> [docs/cleanup] updated TimmAttentionWrapper to TimmSparseAttention 

CHANGELOG.md, README.md, examples/cifarMetaformer.py, tests/test_attentions.py, xformers/components/attention/base.py, xformers/components/attention/pooling.py, xformers/components/attention/visual.py, xformers/factory/block_factory.py
Fixes #319. Note that to reproduce the paper you need the Conv2DFeedforward introduced here #321, and a metaformer-like structure
=> [feat] Adding Visual Attention

xformers/factory/block_factory.py
When creating the model, `use_triton` isn't passed to the Norm module in the factory. This is required when skipping the triton-based layer norm implementation when using BFloat16.
=> Pass `use_triton` flag to LayerNorm module

BENCHMARKS.md, CHANGELOG.md, tests/test_core_attention.py, xformers/benchmarks/benchmark_causal_blocksparse.py, xformers/benchmarks/utils.py, xformers/components/attention/core.py, xformers/components/attention/utils.py
=> Blocksparse switch revisions

CHANGELOG.md, xformers/components/attention/pooling.py
Not a functional bug, but the projection layers were built for something like poolformer (using the pooling attention mechanism), even if not being used. This took some space in memory, and led to a false number of exposed parameters for the whole model. There was one flag missing to tell xformers that this mechanism does not require projections.
Issue caught when having a look at #347
=> [hotfix][minor] Poolformer does not need projections

CHANGELOG.md, xformers/factory/block_factory.py, xformers/factory/model_factory.py
=> [fix] Layer positions labelling & layernorm

xformers/sparse/_csr_ops.py, xformers/sparse/csr_tensor.py
When training a transformer that uses SparseCSRTensor, I had a bug "Expected D1.is_contiguous() to be True but got False. It happened during the evaluation time. I also had bug when the batch size was 1 or when using only 1 GPU. 
These little fixes solved my problem and they would be useful since I need to release a model that uses xformers. 
=> Add .contiguous() to several tensor in the sparse folder

tests/test_favor.py
PyTorch's `torch.eig` was deprecated since version 1.9 and is being removed by https://github.com/pytorch/pytorch/pull/70982
=> Update deprecated torch.eig

tests/test_nystrom_attention.py, xformers/components/attention/core.py, xformers/components/attention/nystrom.py
Fixes #360. When using `key_padding_mask`, nystroformer attention was raising NaN because of masking on calculation of `kernel_1`. Although `key_padding_mask` was used as `mask_1`, key was the compressed by pooing already.
Following the original code of [Nystromformer](https://github.com/mlpen/Nystromformer/blob/main/code/attention_nystrom.py), I have updated the corresponding codes. Concretely, padding tokens in query and key were masked before pooling, and masks of calculation in `kernel_1` and `kernel_2` were deleted.
After that, I have confirmed that `NaN` was not raised. In addition, I have deleted replacement of NaN with random values in the test because existing NaN in output are not expected.
Anyone in the community is free to review the PR once …
=> Fix nystromformer attention

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_simt_tile_iterator_residual.h, xformers/ops.py
Implemented for:
- SIMT (P100 + V100 f32)
- A100
NOTE: In any case, when using f16, we still want `num_keys % 2 == 0` to read entire smem banks at once.
For this special case, and for V100, we will pad the inputs (in a further PR, because it also requires to implement masking)
**TEST PLAN**
- Tested on P100/V100 that it does not change the runtime of the kernels
- Added test cases
<details>
<summary>A100 perf</summary>
20134bb = this PR
170f9b0ef1cea3a543c8c507a375469826c822c5 = main
```
[-------------------------------- attention (attn_bias=<class 'NoneType'>) --------------------------------]
|  20134bb  |  vanilla  |  170f9b0ef1cea3a543c8c507a375469826c822c5
1 threads: -------------------------------------------------------------------------------------------------
f16 fwd_gen B=256, …
```
=> Support partial tiles for attention fw/bw

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu
This gives us more control on what variables we keep in registers. Does not change performance for now, but will be useful later for when we want to have some dynamic seqlengths.
Performance on A100:
30e73b1 = this PR
170f9b0ef1cea3a543c8c507a375469826c822c5 = main
```
[-------------------------------- attention (attn_bias=<class 'NoneType'>) --------------------------------]
|  30e73b1  |  vanilla  |  170f9b0ef1cea3a543c8c507a375469826c822c5
1 threads: -------------------------------------------------------------------------------------------------
f16 fwd_gen B=256, M=128, K=16     |     37.9  |     60.5  |                     38.0                 
f32 fwd_gen B=256, M=128, K=16     |     89.8  |    125.3  |                     92.4                 
f16 fwd_gen B=256, M=128, K=32     | …
```
=> Attention Forward: Refactor to no longer use pytorch's TensorAccessors

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h, xformers/components/attention/csrc/cuda/mem_eff_attention/epilogue_rescale_output.h
Significant performance improvements for `K <= 64`. Performance is worse for `K >= 64`. Let's keep this as a TODO (https://github.com/facebookresearch/xformers/issues/380) for later
30e73b1 or 170f9b0ef1cea3a543c8c507a375469826c822c5: reference
7e34b16: This PR
**A100**
```
[---------------- attention (attn_bias=<class 'NoneType'>) ---------------]
|  7e34b16  |  vanilla  |  30e73b1
1 threads: ----------------------------------------------------------------
f16 fwd_gen B=256, M=128, K=16     |     42.3  |     61.6  |     37.9
f32 fwd_gen B=256, M=128, K=16     |     73.4  |    159.2  |     89.8
f16 fwd_gen B=256, M=128, K=32     |     43.7  |     61.8  |     38.9
f32 fwd_gen B=256, M=128, K=32     |     75.3  |    173.4  |     91.3
f16 fwd_gen B=256, M=128, K=64     |     52.6  |     62.7 …
```
=> AttentionForward: Change block size to 64x64

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
<details>
<summary>V100/P100 perf fw</summary>
```
[----------------------------------- attention (attn_bias=<class 'NoneType'>) ----------------------------------]
|  1722b913_causal  |  74460174_outputrf  |  vanilla
1 threads: ------------------------------------------------------------------------------------------------------
(Quadro_GP100)          f32 fwd_gen B=256, M=128, K=16     |         162.3     |          163.0      |    300.5
f16 fwd_gen B=256, M=128, K=16     |         168.0     |          167.1      |    221.2
f32 fwd_gen B=256, M=128, K=32     |         177.6     |          178.3      |    284.3
f16 fwd_gen B=256, M=128, K=32     |         196.4     |          196.7      |    239.2
f32 fwd_gen B=256, M=128, K=64     |         236.2     |          235.8      |    337.4
f16 …
```
=> MemEffAttention: Add causal support

xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
LSE was padded with uninitialised values rather than `inf` as expected
| PR | Title |  Merges Into  |
|:--:|:------|:-------------:|
|#391|[MMA_FROM_SMEM_IT_RES] Fix padding of LSE in forward|**N/A**|
|#392|[MMA_FROM_SMEM_IT_RES] Copy over files from cutlass|#391|
|#393|[MMA_FROM_SMEM_IT_RES] Change how residuals are handled|#392|
=> [MMA_FROM_SMEM_IT_RES] Fix padding of LSE in forward

xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/make_residual_last.h, xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_access_iterator_residual_last.h, xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_iterator_residual_last.h, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h, xformers/ops.py
Changes how we deal with residuals for the right-hand operand of MM from shared memory. This is used on the fw and bw pass, and enables to support arbitrary sequence lengths.
<details>
<summary>P100/V100 bw (causal)</summary>
```
[-------------- attention backward (attn_bias=<class 'xformers.ops.LowerTriangularMask'>) ---------------]
|  a10cd6d8_it2  |  f527a89c_main  |  vanilla
1 threads: -----------------------------------------------------------------------------------------------
(Quadro_GP100)          f32 fwd_gen B=256, M=128, K=16     |       491.5    |        492.0    |    617.9
f16 fwd_gen B=256, M=128, K=16     |       421.3    |        420.8    |    503.1
f32 fwd_gen B=256, M=128, K=32     |       601.2    |        601.9    |    696.0
f16 fwd_gen B=256, M=128, K=32     | …
```
=> [MMA_FROM_SMEM_IT_RES] Change how residuals are handled

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* __->__ #395
**TEST PLAN**
```
CUDA_VISIBLE_DEVICES=1 CUDA_LAUNCH_BLOCKING=1 time python -m pytest tests/test_mem_eff_attention.py
```
The tests run in ~22s on my machine now
=> Fix bugs in backward. More/faster tests

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/epilogue_pipelined.h, xformers/components/attention/csrc/cuda/mem_eff_attention/epilogue_rescale_output.h, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* __->__ #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
- We still accumulate in f32 in gmem (or RF) when `scalar_t` is f16 (for numerical stability reasons)
- Added tests cases to trigger gmem accumulation (K>128 && M>128)
- Merged the 2 epilogue we have (so now we are also using the pipelined epiloque in forward)
- Bonus: this makes backward faster because we avoid 2 casts (output+grad)
=> outputf16: Change forward's output to match input dtype

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16_aligned.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16_aligned_k128.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16_aligned_k64.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16_k128.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/backward_bf16_k64.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/forward_bf16.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/forward_bf16_aligned.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernels/generate_kernels.sh, xformers/ops.py
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* __->__ #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
Performance is similar to f16
*(bf16 is only available on A100)*
<details><summary>A100 fw</summary>
```
[------------- attention (attn_bias=<class 'NoneType'>) -------------]
|  optimized  |  vanilla  |   flash
1 threads: -----------------------------------------------------------
f16 B=16, M=4096, K=40     |      891.3  |   1940.7  |
b16 B=16, M=4096, K=40     |      891.1  |   1991.0  |
f16 B=16, M=16384, K=40    |    12748.1  |  30657.1  |
b16 B=16, M=16384, K=40    |    12745.9  |  31955.2  |
f16 B=160, M=4096, K=128   | …
```
=> bf16: Add support in fw/bw

xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* __->__ #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
=> mmafix: Fix matmul out-of-bounds for small dimensions with preloading

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* __->__ #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
We now correctly skip the parts of the attention matrix that we shouldn't compute.
=> causalfix: Fix causal after iteration inversion

xformers/components/attention/csrc/cuda/mem_eff_attention/gemm/custom_mma_base.h, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm/custom_mma_multistage.h, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm/custom_mma_pipelined.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
* #443
* #442
* #440
* #439
* #438
* #434
* __->__ #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
We also try to reuse K for the first matmul between iterations, if it is possible
I also changed how we represent shared-memory to make it easier to change/hack
=> prologuemma: Prefetch tensors before mmuls

xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_access_iterator_residual_last.h
* #443
* #442
* #440
* #439
* #438
* __->__ #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**PERFORMANCE F16**
<details>
<summary>A100 fw</summary>
```
[--------------------------------------------------------------------------------------------- attention (attn_bias=<class 'NoneType'>) --------------------------------------------------------------------------------------------]
|  prologuemma_5b7b8db  |   flash    |  vanilla  |  mma_pipeline_01fa622  |  noinit_69206e9  |  bw_preproc_e351b21  |  outputf16_64be278  |  f16_4116eb4  |  custommma_b99b79b  |  causalfix_3dbafca
1 threads: ---------------------------------------------------------------- …
```
=> p100nvcc: Workaround a compiler bug on P100

xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
* #443
* #442
* __->__ #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
Will make it possible to support Nested Tensors in pytorch.
This is not currently exposed to end-users, as we need to figure
out how we pass the cumulative sequence lengths to the kernels
=> seqlen: Support variable sequence lengths

xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
* __->__ #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
=> v100nvcc: work around a compiler bug in V100

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu
* #452
* #451
* #449
* #448
* #447
* #446
* __->__ #445
* #444
**PERFORMANCE COMPARISON**
<details>
<summary>A100 fw</summary>
```
[--------------------------------------- attention (attn_bias=<class 'NoneType'>) ---------------------------------------]
|  37_regfix_85c0fb4[cutlass]  |  vanilla  |  flash[flshatt]  |  37_noqs_1b917ab[cutlass]
1 threads: ---------------------------------------------------------------------------------------------------------------
f16 B=16, M=4096, K=40     |              873.6           |   1942.5  |                  |             882.0        
f16 B=16, M=16384, K=40    |            12504.9           |  30670.0  |                  |           12638.1        
f16 B=160, M=4096, …
```
=> regfix: Fix regression with cu seqlen PR

xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
* #459
* #458
* #456
* #454
* __->__ #453
* #452
=> bwinline: Forceinline all functions of the bw

tests/test_mem_eff_attention.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/ops.py
* #459
* __->__ #458
* #456
* #454
* #453
* #452
**SUMMARY**
Also:
- updated benchmarks to reflect the real-world scenario where we chunk a packed qkv - for both fw/bw.
- added coverage for chunking in tests
**PERFORMANCE IMPACT**
<details>
<summary>A100 bw (new benchmarks)</summary>
```
[---------------------------------- attention backward (attn_bias=<class 'NoneType'>) ----------------------------------]
|  48_chunk3_31735f9  |  45_bwpacked_e53c5f3  |  vanilla  |  47_bwpackedgrad_9bacdf6
1 threads: --------------------------------------------------------------------------------------------------------------
f16 B=384, M=197, H=1, K=88    |          560.7      |           663.9       |   2265.7  | …
```
=> chunk3: Add custom operator to avoid torch.cat in BW

xformers/helpers/test_utils.py
Fixes fails in test_feedforward.py and test_block_factory.py
Even though windows pytorch is built with CUDA it doesn't support NCCL, only GLOO or MPI.  So needed to add a check if on windows to do the test_block_factory.py and test_block_factory.py tests without failing.
Fixes #464 
=> fix failing tests #464 due to windows distributed using gloo not nccl

tests/test_mem_eff_attention.py, xformers/ops.py
* __->__ #469
<details>
<summary>A100 bw</summary>
```
[--------------------------------- attention backward (attn_bias=<class 'NoneType'>) ---------------------------------]
|  flash[flshatt]  |  vanilla  |  fwbw[fctls_bflsh]  |  48_chunk3_31735f9[cutlass]
1 threads: ------------------------------------------------------------------------------------------------------------
f16 B=384, M=197, H=1, K=64    |        232.7     |   1813.9  |          240.3      |              391.7         
f16 B=1024, M=197, H=1, K=64   |        577.0     |   4746.9  |          582.8      |              876.9         
f16 B=32, M=197, H=16, K=64    |        296.2     |   2434.6  |          303.2      | …
```
=> fctls_bflsh: New OP that combines cutlass's fw + flash's bw

.circleci/config.yml, README.md, packaging/conda/xformers/meta.yaml
=> update README.md for dev packages

xformers/__init__.py, xformers/components/attention/__init__.py, xformers/components/attention/blocksparse.py, xformers/components/attention/core.py, xformers/components/attention/favor.py, xformers/components/attention/nystrom.py, xformers/components/attention/ortho.py, xformers/components/attention/scaled_dot_product.py, xformers/components/feedforward/fused_mlp.py, xformers/components/feedforward/mixture_of_experts.py, xformers/components/input_projection.py, xformers/components/multi_head_dispatch.py, xformers/factory/block_factory.py, xformers/factory/hydra_helper.py, xformers/factory/model_factory.py, xformers/factory/weight_init.py, xformers/sparse/blocksparse_tensor.py, xformers/triton/layer_norm.py, xformers/triton/softmax.py, xformers/triton/utils.py
This introduces the use of a dedicated logger throughout the library instead of relying on Python's root logger.
Test Plan: CI + local ad-hoc script:
```
$ ./test_logging.py
2022-10-10 15:20:15,468 WARNING MainThread xformers WARNING:
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
```
=> Use dedicated logger instead of the root one

.circleci/config.yml, xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/epilogue_predicated_tile_iterator.h
We were using torchvision `0.2.2` before, which is fairly old - not sure why.
For some reason, this also updates the clang-format version (I guess?), so I needed to apply it again. Now it matches the output of my local clang-format at least - the difference was only for a single file
=> Fix CI by updating torchvision

tests/test_core_attention.py, xformers/components/attention/core.py
Repeat mask when batch dims don't match. 
Should this be handled in the sparse case as well?
=> Repeat mask when batch dims don't match

tests/test_block_factory.py, xformers/components/attention/global_tokens.py, xformers/components/attention/local.py, xformers/components/attention/ortho.py, xformers/components/attention/random.py, xformers/factory/block_factory.py
Issue with not being able to use AttentionMask with encoder and decoder blocks.
=> enable AttentionMask in Block Factory

xformers/ops/__init__.py, xformers/ops/memory_efficient_attention.py, xformers/ops/unbind.py
* #518
* #511
* #510
* #509
* #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* #487
* __->__ #486
**SUMMARY**
As discussed offline with @fmassa , will make extending new operators clearner
=> Split xformers.ops

tests/test_swiglu.py, xformers/benchmarks/benchmark_swiglu.py, xformers/ops/__init__.py, xformers/ops/swiglu.py
* #518
* #511
* #510
* #509
* #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* __->__ #487
* #486
=> ops.swiglu: Tests, baseline, benchmarks

.gitmodules, tests/test_swiglu.py, xformers/components/swiglu/cuda/gemm_fused_operand_sum.cu, xformers/components/swiglu/swiglu_packedw.cpp, xformers/ops/swiglu.py
* #518
* #511
* #510
* #509
* #505
* #508
* #504
* #491
* __->__ #502
* #490
* #498
* #488
* #487
* #486
***PERFORMANCE A100**
```
operandfused_all <- THIS PR
SwiGLUPackedFusedOp <- previous pr
[--------------------------------------- swiglu_bw ---------------------------------------]
|  operandfused_all  |  eager   |  SwiGLUPackedFusedOp
1 threads: --------------------------------------------------------------------------------
b16    B=9456, I=1536, H=4096  |       2227.6       |  2708.3  |         2341.6      
f16    B=9456, I=1536, H=4096  |       2337.5       |  2705.8  |         2339.1      
f16.ac B=9456, I=1536, H=4096  |       2630.5       |  2998.5  |         2806.6      
b16    B=4440, I=1536, H=4096  | …
```
=> SwiGLU further optimization in MLP bw

tests/test_swiglu.py, xformers/benchmarks/benchmark_swiglu.py, xformers/components/swiglu/cuda/dual_gemm_silu_identity_mul.cu, xformers/components/swiglu/swiglu_op.cpp, xformers/components/swiglu/swiglu_packedw.cpp, xformers/ops/swiglu.py
* #518
* #511
* #510
* #509
* #505
* #508
* __->__ #504
* #491
* #502
* #490
* #498
* #488
* #487
* #486
```
[-------------------------- swiglu_fw --------------------------]
|  optimized  |  eager 
1 threads: ------------------------------------------------------
b16    B=9456, I=1536, H=4096 bias  |    1338.5   |  1568.4
b16    B=9456, I=1536, H=4096 nobi  |    1268.3   |  1477.1
f16    B=9456, I=1536, H=4096 bias  |    1305.3   |  1607.4
f16    B=9456, I=1536, H=4096 nobi  |    1291.7   |  1493.0
f16.ac B=9456, I=1536, H=4096 bias  |    1445.1   |  1754.7
f16.ac B=9456, I=1536, H=4096 nobi  |    1434.0   |  1640.5
b16    B=4440, I=1536, H=4096 bias  |     580.7   |   726.5
b16    B=4440, I=1536, …
```
=> SwiGLU: Support for no bias

xformers/benchmarks/benchmark_transformer.py, xformers/benchmarks/utils.py
* #518
* #511
* #510
* #509
* __->__ #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* #487
* #486
=> Benchmarks for entire models

xformers/ops/memory_efficient_attention.py
* #518
* #511
* __->__ #510
* #509
* #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* #487
* #486
=> MemEff: Raise if wrong bias

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops/memory_efficient_attention.py
Implement #522.
- Add a new argument `has_custom_scale` to memory efficient attention `forward`. When it is true, we assume the query state weights are scaled in advance so they won't be scaled again in kernels. This is required especially for T5 models.
- Add a new flag `SUPPORTS_CUSTOM_SCALE` to indicate whether a memory efficient op supports custom scale. In this PR we only enable `MemoryEfficientFlashAttentionOp` to align the API change and experiments. If everything goes well, I'll support `MemoryEfficientAttentionOp` in a follow-up PR (I'm not sure if the CUTLASS one can be supported without first changing CUTLASS kernel. It'd be great if someone could help confirm).
Updated based on review comments:
- New attribute `has_custom_scale: bool = False` in `AttentionOpDispatch`.
- New …
=> Allow custom softmax in memory efficient attention

.github/workflows/wheels.yml
Adds Github Workflow to build pip wheels. Fixes #473.
- changing one line and then waiting a couple of hours to find out that I made a typo is not what I would define as fun, but I definitely learned a lot which is why I wanted to do this in the first place.
- #473
- The xformers team should decide on the release and delivery processes of the pip wheels first, then the docs can be updated.
=> Build Pip Wheels

tests/test_triton_blocksparse.py, tests/test_triton_softmax.py, xformers/benchmarks/benchmark_triton_layernorm.py, xformers/benchmarks/benchmark_triton_softmax.py, xformers/benchmarks/utils.py, xformers/components/attention/blocksparse.py, xformers/triton/k_softmax.py, xformers/triton/layer_norm.py, xformers/triton/softmax.py, xformers/triton/utils.py
Fixes #353. Goal was not to touch softmax initially, but it turns out that enabling bfloat16 can die on triton's softmax (tl.max() cannot be lowered in bf16), hence the double fix
=> [triton] bfloat16 aware blocksparse & softmax

xformers/ops/unbind.py
On Python 3.7.15 (current Google Colab), #527 still raise SyntexError.
```
File "/usr/local/lib/python3.7/dist-packages/xformers/ops/unbind.py", line 99
return None, *(grad.unbind(dim=ctx.dim))
^
SyntaxError: invalid syntax
```
According to these info,
- https://bugs.python.org/issue32117
- https://stackoverflow.com/questions/47272460/why-is-starred-iterable-unpacking-in-a-return-statement-invalid-syntax-without-p
It is a matter of the "return statement", not only unpacking things. So it should be,
```
return (None, *grad.unbind(dim=ctx.dim))
```
I confirmed this fix works on 3.7.15.
It was discussed at https://github.com/facebookresearch/xformers/commit/0428e12accab31cc3a5677b47b61ba8e7b6dfad2#r91033157
Anyone in the community is free to review the PR …
=> fix error on Python 3.7 unpacking tuple in return statements

tests/test_mem_eff_attention.py, xformers/ops/memory_efficient_attention.py
This was not visible before because the test was creating tensors of the wrong dtype, which when casted to the right dtype would yield contiguous tensors
=> FlashAttention needs contiguous gradients

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/debug_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h
* #467
* #549
* #540
* __->__ #539
... by reducing the number of ATen imports, and skipping them altogether when building the actual kernels
13mn -> 9mn on Sm61 (CI, does not build flash)
=> Improve build time by ~30%

.github/workflows/wheels.yml, packaging/conda/build_conda.py, setup.py
* #467
* __->__ #549
* #540
* #539
=> Reduce binary size - no debug info for binaries

xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
Backport of https://github.com/pytorch/pytorch/pull/90389/files
Does not seem to affect performance on A100
<details>
<summary>A100 BW</summary>
```
[------------- attention backward (attn_bias=<class 'NoneType'>) -------------]                                                                                                                                                                                                                                               
|  no_register_kw  |  vanilla  |  cutlass 
1 threads: --------------------------------------------------------------------
f16 B=384, M=197, H=1, K=88    |        616.1     |   2261.1  |     621.0
f16 B=384, M=197, H=1, K=80    |        585.6     |   1918.6  |     589.4
f16 B=384, M=197, H=1, K=64    | …
```
=> C++17: Remove register kw

.circleci/config.yml, requirements-benchmark.txt, xformers/benchmarks/benchmark_vit_timm.py
* #571
* #570
* #568
* #561
* #560
* #557
* #495
* #555
* __->__ #567
It now takes an argument: https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html
Change in pytorch lightning:
https://github.com/Lightning-AI/metrics/commit/20eab4309b9bcde7a3157a1e3fb72711048d6c7c
Somehow this is failing with a SEGFAULT on my A100 (in a triton kernel):
```
#0  0x00007fffc0f62e10 in ?? () from /lib/x86_64-linux-gnu/libcuda.so
#1  0x00007fffc0f9303c in ?? () from /lib/x86_64-linux-gnu/libcuda.so
#2  0x00007fffc0f2ea13 in ?? () from /lib/x86_64-linux-gnu/libcuda.so
#3  0x00007fffc0f94603 in ?? () from /lib/x86_64-linux-gnu/libcuda.so
#4  0x00007fffc119e4a0 in ?? () from /lib/x86_64-linux-gnu/libcuda.so
#5 …
```
=> Fix CI after torchmetrics update

.circleci/config.yml, xformers/info.py, xformers/ops/common.py, xformers/ops/fmha/common.py, xformers/ops/fmha/cutlass.py, xformers/ops/fmha/flash.py, xformers/ops/fmha/small_k.py, xformers/ops/fmha/triton.py
* #571
* #570
* #568
* __->__ #561
* #560
* #557
* #495
* #555
* #567
=> Refactor5: Generic way of registring operators for xformers.info

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/ops/fmha/__init__.py, xformers/ops/fmha/flash.py, xformers/ops/fmha/tensor_with_seqlen.py
* Fix wrong sanity check for LSE that didn't apply with varying seqlen
* CUTLASS: Fixed LSE shape when used with varying seqlen
* Add test for backward with `TensorWithSeqLen`
* Fix gradient flow through `TensorWithSeqLen.from_tensor_list` (+ add test)
* `TensorWithSeqLen`: fix with __getitem__ operation (and others with input tensors that are nested within the arguments)
=> TensorWithSeqLen: multiple fixes

.github/workflows/wheels.yml
Upload source distribution to PyPi. Continuation of #588 
I am unsure if this is strictly necessary since we basically upload wheels for every supported platform, but it won't hurt `¯\_(ツ)_/¯`
Related #533 
I have considered consoldating  the `env` from the last 2 steps to the global env, but I don't want any steps (especially external actions) to access the token.
Example sdist:
https://test.pypi.org/project/formers/0.0.16rc379/#files
=> Upload source distribution to PyPi

xformers/ops/fmha/__init__.py, xformers/ops/fmha/common.py
=> MHA: Stricter input validation

.github/workflows/wheels.yml, packaging/compute_wheel_version.py
Support using `v` as prefix for a tagged version.
Fix RC release error.
The cpu test fails because of something unrelated to this PR.
=> Support v prefix for tags

xformers/csrc/swiglu/swiglu_packedw.cpp
Building the most recent checkout of xformers on windows fails, due to an import order change. Reversing just the import order fixes the issue and compilation succeeds.
Relevant diff: https://github.com/facebookresearch/xformers/commit/1191f035e8aa06241850dedf2c20d66f5b3ba575#diff-01fa83cea99fafa71b4fac634463ca400283548bb8ca206ee56e02c9856929a8L2
Prior to this change, the order was:
```
#include <ATen/core/dispatch/Dispatcher.h>
#include <ATen/autocast_mode.h>
```
After this change, the order was 
```
#include <ATen/autocast_mode.h>
#include <ATen/core/dispatch/Dispatcher.h>
```
In this order, compilation fails on `xformers/csrc/swiglu/swiglu_packedw.cpp`. Reverting to previous order allows the change to succeed.
Anyone in the community is free to review …
=> Fix issue with import order changing in 1191f03 breaking windows builds

.github/workflows/wheels.yml, MANIFEST.in, setup.py
Fixes an issue introduced by #590
we pin pytorch's version while generating the wheels, and since we re-use the runner to generate the source distribution; the pinned version gets carried over.
This PR unpins the version.
Maybe it would make sense to use a different runner for the source distribution, but this change will be required nonetheless, since pytorch is pinned per default in requirements.txt.
=> Relax pytorch dependency version

packaging/conda/xformers/meta.yaml
Adds missing einops dependency (introduced in #557) to the Conda package.
- I mean, it's not the most fun PR ever :)
=> Adds missing einops dependency to Conda package

.github/workflows/win-build.yml, setup.py
Windows build is currently broken (cc @AbdBarho ) - I've reached out to @tridao to get a fix in Flash-Attention repo.
This is because we updated flash to v0.2.4 (https://github.com/facebookresearch/xformers/commit/eaf8c2e90988216e72504b0fcb0f0d4f7020fcb3), which was needed to fix conda builds (because conda builds can't depend on `einops`, which is a pip-only package)
=> Windows build with Flash-Attention v0.2.4

xformers/csrc/attention/cuda/fmha/attention_backward_generic.cu, xformers/csrc/attention/cuda/fmha/attention_forward_generic.cu, xformers/ops/fmha/__init__.py
The reproducibility issue mentioned in #618. It can be warned or the program can be stopped, especially in runtime environments where torch.use_deterministic_algorithms(True) is used. I have also included a sentence in the documentation.
For testing, I have run the script in the link below. The results are also included.
https://gist.github.com/takuma104/748c2d12abc4ce9111c1202b1f0efbc6
- [Y] Did you have fun?
- [Y] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [Y] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [Y] Did you make sure to update the docs?
- [N] Did you write any new necessary tests?
- [N] Did you update the …
=> memory_efficient_attention()  nondeterministic warning

packaging/build_conda.py
* __->__ #639
fairinternal has no useful tag to count from.
Just store the commit hash itself.
=> simplify GIT_TAG in conda package

tests/test_attentions.py, xformers/components/attention/scaled_dot_product.py
Fixes #655 
This PR allows a class-level causal attention mask for fixed sequence-length tasks; otherwise it creates a new mask on-the-fly in the forward pass to disentangle the mask from sequence length which can vary between batches in tasks like MT.
=> fix mask-tying to sequence length

xformers/ops/unbind.py
Reduce overhead in stack_or_none, tensor.storage() is expensive (3us each call) since it needs to go across Python and Cython. Based on a local benchmark, this can reduce stack_or_none on two tensors from 20us into 12 us.
=> reduce overhead in stack_or_none

docs/requirements.txt, requirements-test.txt, requirements.txt
Bump pyre-check and pyre-extensions versions, since the outdated current version blocks projects that use xformers to use newer Pyre versions.
=> Bump pyre extensions versions

tests/test_mem_eff_attention.py, xformers/csrc/attention/cuda/fmha/kernel_forward.h
Causal + dropout_p could potentially be producing incorrect gradients. 
=> Use the absolute index for rng state indexing

setup.py
Fixes an issue when `TORCH_CUDA_ARCH_LIST` contains a two-digit major version, e.g. `10.1`.  Hopefully fairly self-evident how it will now work (and how/why it was previously broken).
=> fix: handle CUDA arch major >= 10

docs/source/xformers_mingpt.ipynb, examples/microGPT.py
Fixes #818 
The pytorch lightning version introduced changes in `Trainer` class:
* keyword argument `gpus` is no longer used
* instead, you might use `devices=1` with `accelerator="gpu"`
=> Adopted `gpus` parameter for newer version of pl

.github/workflows/conda.yml, packaging/compute_wheel_version.py
We had this error because the version was defined twice:
```
Invalid version: '0.0.23.dev661.dev661+git.fbbfb38'.
```
=> Fix conda build

xformers/csrc/attention/cuda/fmha/kernel_forward.h
Fixes issues originally reported here https://github.com/pytorch/pytorch/issues/112577
- [x ] Did you have fun?
- [ x] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
=> Fix bug in mem_eff kernel with attention mask and MQA

xformers/ops/fmha/triton_splitk.py
Windows builds are failing on Triton import in `triton_splitk.py` after it was made unconditional recently (discovered in https://github.com/facebookresearch/xformers/pull/978). This PR fixes them by making it conditional again
=> Make Triton import conditional

examples/README.md
Fixes (#1006) a broken link in the README.md under examples pointing to Lighning AI tutorials on CIFAR. 
(did not create a separate issue, since this is a documentation fix)
=> docs: broken url to lightning ai CIFAR example

setup.py, xformers/csrc/attention/hip_fmha/attention_forward_decoder.cpp, xformers/csrc/attention/hip_fmha/attention_forward_splitk.cpp, xformers/csrc/attention/hip_fmha/ck_attention_forward_decoder.h, xformers/csrc/attention/hip_fmha/ck_attention_forward_decoder_splitk.h
Fixes compilation error in cpp extensions for decoder and splitk decoder.
A few issues were fixed
* fbcode has `-Werror` flag enabled, but OSS did not
* the kernel wrapper definitions hid the virtual functions defined at base invoker
* while hiding, the signature was also changed, so I had to add an extra casting step to make the compiler happy
* while testing the change I got spurious accuracy errors, which I got rid of by copying the args struct instead of using a reference, as it's allocated on stack somewhere and the existing way is not safe
`# pytest /xformers/tests/test_mem_eff_attention.py -k decoder` (a few times) …
=> Try fix ck decoder compilation in fbcode (2/n)

xformers/csrc/attention/cuda/fmha/kernel_backward.h
TLDR; I think the FMHA backward kernel uses more scratch memory than it needs, aside from padding due to 128-bit alignment and tile sizes.
FMHA backward's scratch space for gK and gV is set up to be: [num_k_splits * align_up(num_keys, kBlockSizeJ) * align_up(dim, kBlockSizeI)](https://github.com/facebookresearch/xformers/blob/main/xformers/csrc/attention/cuda/fmha/kernel_backward.h#L858-L871) repeated over batch and heads.
Given that each CTA computes unique tiles of gK and gV, this means for every gK/gV tile, `align_up(num_keys, kBlockSizeJ) * align_up(dim, kBlockSizeI)` accum elements are reserved.
I might be totally off, but my understanding is that the gK and gV accumulator pointers aren't even offset by something relating to key_start, which means the same `kBlockSizeJ` rows will be …
=> Change workspace size in fmha backward

xformers/csrc/attention/hip_fmha/ck_tiled_fmha_batched_forward.h, xformers/csrc/attention/hip_fmha/ck_tiled_fmha_batched_infer.h
Without the fixing,  `seqlen_k == 0` will lead to `NaN` in the fmha forward output.  
The following scripts can be used to verify the issue:
```bash
import torch
from xformers.ops import fmha
def main():
xattn_q_seqlen=[1, 2, 1, 2]
xattn_kv_seqlen=[0, 2, 0, 2]
options = {
'device': 'cuda',
'dtype': torch.float16
}
axq = torch.randn((1, 6, 2, 68), **options)
axk = torch.randn((1, 4, 2, 68), **options)
axv = torch.randn((1, 4, 2, 68), **options)
xattn_bias = fmha.attn_bias.BlockDiagonalMask.from_seqlens(
q_seqlen=xattn_q_seqlen, kv_seqlen=xattn_kv_seqlen
)
print("seqstart_q:")
print(xattn_bias.q_seqinfo.seqstart_py)
print("seqstart_k:")
print(xattn_bias.k_seqinfo.seqstart_py)
print(f"{xattn_bias=}")
y = fmha.memory_efficient_attention_forward(
axq,
axk,
axv,
attn_bias=xattn_bias,
p=0.0, …
```
=> Enable support of seqlen_k == 0 for fmha forward

xformers/benchmarks/benchmark_attn_decoding.py, xformers/ops/fmha/triton_splitk.py
Integrate the int4kv standalone test to the benchmark `benchmark_attn_decode.py`
=> Integrate int4kv to benchmark_attn_decode.py

xformers/ops/swiglu_op.py
A small PR. This PR addresses the issue of disabling fused swiglu in swiglu_op.py. The original code directly disabled the support for fused swiglu, with the comment "Let's disable autocast in bf16 until this issue is fixed". After my testing, PyTorch 2.0.0 has already fixed this bug. Therefore, we should add a judgment for the PyTorch version, and then determine whether to support fused swiglu, instead of directly disabling swiglu as before. This makes it more user-friendly.
=> The original code directly disabled the support for fused swiglu, but pytorch2.0.0 has fixed the issue in autocast of bf16.

xformers/benchmarks/benchmark_attn_decoding.py, xformers/ops/fmha/triton_splitk.py
Fixes a performance regress for FA decode. Changes are related to the function `get_split_k()`, which is to compute the number of splitK in the fa decode in Triton.
This PR also added a test to verify the correctness of different implementations of FA decoders, you can run the tests as:
`pytest benchmark_attn_decoding.py -v`
=> update get_split_k to fix a performance regression on FA decode

docs/source/tutorials/triton.rst
Fixes issue #1055
The current documentation on triton fused linear layers used the wrong class name, FusedLinearLayer instead of FusedLinear, which is the name currently used in the module. This PR updates the docs to reflect the current name.
=> Updated FusedLinearLayer to FusedLinear in the triton tutorial page

xformers/ops/fmha/ck.py
It makes no sense to use `_check_large_shapes()` to add unintended restriction to the input sizes of the CK fmha fwd/bwd operator.  So just remove it.
=> Remove _check_large_shapes checking in fmha/ck.py

tests/test_mem_eff_attention.py, xformers/csrc/attention/hip_fmha/attention_backward_generic_ck_tiled.cpp, xformers/csrc/attention/hip_fmha/attention_forward_generic_ck_tiled.cpp
Add torch.compile support for CK ops , to avoid graph break in pt2 workflow.
From [D61453034](https://www.internalfb.com/diff/D61453034)
=> Add torch compile support for ck attention op

examples/llama_inference/generate.py
`torch.load` without `weights_only` parameter is unsafe. Explicitly set `weights_only` to False only if you trust the data you load and full pickle functionality is needed, otherwise set `weights_only=True`.
If `weights_only=True` doesn't work for some cases, then explicit `weights_only=False` should be used.
Found with https://github.com/pytorch-labs/torchfix/
=> Use weights_only for load

.github/workflows/rocm_ci.yml
As titled, it syncs rocm_ci workflow from the rocm fork, to make the maintenance easier
The workflow is supposed to run only in the rocm fork, as there's no ROCm runner in facebookresearch xformers repo for now
=> [ROCm] update rocm_ci workflow from rocm fork

xformers/ops/fmha/__init__.py
It looks like BlockDiagonalMask import was accidentally removed in commit 166fd2e. This commit adds it back.
- [Yes] Did you have fun?
- [Yes] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [No] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- I work at Meta; I discussed this change with xformer maintainer over chat.
- [No] Did you make sure to update the docs?
- [V] N/A
- [No] Did you write any new necessary tests?
- [V] N/A
- [No] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? (if needed)
- [V] N/A …
=> [fix] Add back BlockDiagonalMask import

xformers/csrc/swiglu/swiglu_packedw.cpp
According to the docs (https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function) forward() method should not be called directly, apply() method have to be used instead. After removing forward call, activation checkpointing starts working.
Fixes #1126 
=> [fix] Fix the activation checkpointing when using SwiGLUPackedFusedOp

xformers/csrc/swiglu/cuda/dual_gemm_silu_identity_mul.cu, xformers/csrc/swiglu/cuda/epilogue_lhs_activation_and_mul.h
Generalization of dual_gemm_silu_identity_mul to use custom activation function.
- renamed dual_gemm_silu_identity_mul* to dual_gemm_lhs_activation_and_mul*
- added a template parameter for the activation function to dual_gemm_lhs_activation_and_mul*.
- added customizable epilogue class (EpilogueLHSActivationAndMul) with the same template parameter.
Fixes #1140
=> [refactor] Generalization of dual_gemm_silu_identity_mul

xformers/csrc/swiglu/swiglu_packedw.cpp
Without this fix the number of tensors saved during recomputation is equal to 0. 
- moved at::AutoDispatchBelowADInplaceOrView guard after ctx->get_saved_variables().
Fixes #1151.
=> [fix] Fix activation checkpointing of SwiGLU when AMP is enabled.

tests/test_swiglu.py, xformers/ops/swiglu_op.py
Test was passing when it should fail if you corrupt output of swiglu_packedw.
Changes to fix the issue:
- Instead of comparing two custom implementations of SwiGLU with each other, _eager_functional_swiglu is now used as the reference implementation.
- Changed RTOL tolerance for fp16 backward test from `1e-2` to `3e-2` to make 2 failed tests to pass (out of 800 passed).
Fixes #1165
=> [fix] fixed incorrect SwiGLU test_forward_backward test.

xformers/ops/fmha/_triton/splitk_kernels.py
Summary:
Triton 3.2 made some changes to its interpretation of constants (https://github.com/triton-lang/triton/pull/4613) which makes Triton more consistent with pytorch/numpy, but cause some surprising issues with this kernel.  Specifically it seems like log2e is interpreted as float32 in one instance and float64 in another, which leads to reduced prediction accuracy in some cases.
To prevent this, let's make log2e a constant and define it as float32.
=> Use a constant with clearly-defined type for log2e in fwd_kernel_splitK

xformers/ops/sp24.py
This PR fixes an issue in the `Sparse24TensorCuSparseLt._mm()` method where an error message was incorrectly formatted due to a missing f-string prefix. The incorrect string prevented proper variable interpolation in the dtype mismatch error message.
=> Ensure correct dtype interpolation in error message

xformers/csrc/attention/hip_fmha/ck_tiled_fmha_batched_infer_splitkv_smallq_dispatch.h, xformers/csrc/attention/hip_fmha/ck_tiled_fmha_grouped_infer_splitkv_smallq_dispatch.h
This PR corrects the condition checking codes for using `merge nhead_groups with seqlen_q`,  it fixes the failure of `test_forward_gqa`.  
`merge nhead_groups with seqlen_q` is an optimization for improving the performance of decoder inference with mqa/gqa enabled.  But utilizing this optimization requires causal mask is not used (since dimensions merging disturbs the logics for doing causal masking).
=> Correct the condition for using merge_nhead_groups_seqlen_q

setup.py
Nvidia Blackwell cards have been out for a while bu xformers do not formally support them. This PR adds support for them by checking for CUDA12.8 and enabling capability 120. Even though higher capabilities are available in https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list, using 120 is a conservative approach that enables all 50 series cards. This PR definitely solves #1251 and possibly #1228
=> Enabling Blackwell support

xformers/csrc/attention/attention.cpp, xformers/csrc/attention/hip_fmha/attention_forward_generic_ck_tiled.cpp
Full list of changes:
1. Change schema of logsumexp to optional tensor
2. Initialize logsumexp to nullopt
3. Initialize philox_seed and philox_offset to 0
4. Symint'ify the meta function with SymInt and empty_symint (important for torch.compile as well)
Context is https://github.com/ROCm/xformers/issues/65, but let me copy over.
Hi, we want to propose this change so the CK kernel is more compatible with pytorch (more precisely, torch.export and AOTI).
Right now, depending on `compute_logsumexp`, the second return of `efficient_attention_forward_ck`, i.e. logsumexp, is either an actual tensor or an uninitialized tensor. If it is an uninitialized tensor, it would be treated as None in Python. In other words, it functions more like an optional tensor return.
This causes some problems when …
=> Change schema of efficient_attention_forward_ck to have optional tensor return type for better compatibility with torch.export and AOTI 

setup.py
this PR fixes the windows compile issue in #1281 and #1272. </br>It does not fix the root cause as i believe it lies in distutils handling of py_limited_api. The fix consists mitigating the issue at build time. We override the get_ext_filename function and detecting if an extension has been wrongly named and correcting it. for good measure we also control the build and local installation processes to catch any outliers. Also we detect if MSVC is being used and use the correct compiler flags for it. Tested on Blackwell
=> Windows compile Fix

README.md
Add a new install troubleshooting tips about filename being too long that happens on Windows (even when enabled at OS level) Git default config issue.
Just signed the CLA, but if it doesn't work, feel free to reuse the change and make a new Pull Request instead, I do not care about being credited for such a small change 👍 
Fixes #1132 (if users RTFM)
=> Add install troubleshooting tip about longpaths error on Windows when trying to compile
