README.md
Fixes the PyPI links badges in the README, now working after the first PyPI release.
=> [minor] Updating the PyPI links

README.md, tests/test_reversible.py, xformers/factory/block_factory.py, xformers/factory/model_factory.py
Catch a possible broken config, raised in https://github.com/facebookresearch/xformers/pull/45, where some layers would be reversible but not all
=> [CI] catch a broken rev/non-rev config

CONTRIBUTING.md
=> [nit] Update CONTRIBUTING.md

README.md
=> Small fixes to the repo maps

CHANGELOG.md, HOWTO.md, docs/source/conf.py, docs/source/tutorials/blocksparse.rst, docs/source/tutorials/pytorch_encoder.rst, xformers/__init__.py
Updates the changelog and the version number, releasing 0.0.2
=> [chore] v0.0.2 release

requirements.txt, xformers/components/positional_embedding/sine.py
Taking a dependency on Pyre, cleaner code all around and easy to install
=> [hotfix] make Pyre an official dependency

xformers/components/attention/blocksparse.py
Add same checks that exist for attention mask to key padding mask in blocksparse
=> add checks for key padding mask

.isort.cfg, HOWTO.md, examples/microGPT.py
An homage to https://github.com/karpathy/minGPT, this shrinks down the original minGPT code by delegating the trainer code to Lightning, and the modeling code to xFormers. This makes it arguably smaller *and* more flexible than the original (to some extent), and is a good demo of xformers I believe (runs on a single machine, very accessible)
a lot of code is from @SeanNaren, credited  
=> [example] microGPT

xformers/triton/softmax.py
Small convenience, if Triton cannot run for some reason (old cuda setup), log a warning and carry on if possible
=> [minor] Soft fallback if triton softmax fails for any reason

xformers/components/attention/nystrom.py
Same as before, it's just that I discovered triu (upper triangular) in the meantime, I always believed that there was only tril (lowertri) so the code was generating a tril and transposing things
=> [minor] Cleaner Nystrom masking (just discovered triu)

examples/microViT.py
I'll try and see if there are other low-hanging fruits mentioned in #80 and quickly resolve those if that's fine with you. \
Unfortunately, we have to go with a new PR with each.
=> style(microvit): remove einops dependency

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
=> [chore] v0.0.3

.gitignore, .isort.cfg, HOWTO.md, README.md, examples/README.md, examples/microViT.py, examples/requirements.txt
Co-authored-by: Sean Naren <sean@grid.ai>
adding a really nice example from @SeanNaren, instantiate a ViT and train on CiFAR 
TODO:
~~- [ ] possibly make it possible to pick another dataset (from torchvision for instance ?)~~
~~- [ ] command line arguments ?~~
Overall should try to stay below 300 LoC to keep this pedagogical and easy to grok
=> [example] Micro ViT

xformers/components/attention/utils.py
update merge_masks to work for additive attention mask
=> update merge_masks to work for additive attention mask

xformers/components/attention/core.py
Expand dimension in non sparse case in `matmul_with_mask`
=> expand dimension in non sparse case as well

.circleci/config.yml
Turns out that the cache does not include /usr/bin.. so the other PR worked, but just once.. 
=> [CI] Fix, double dose

tests/test_triton_softmax.py
Super minor, check a subcase in the triton softmax
=> [minor][CI] make sure that we check the non contiguous case in softmax

README.md, docs/source/xformers_mingpt.ipynb
Make it possible to directly open a google colab notebook. Ideally we should do the same with the other notebooks from @fmassa I think
=> [doc] Adding a direct colab link for microGPT

xformers/__init__.py, xformers/components/attention/blocksparse.py, xformers/components/attention/core.py, xformers/components/residual.py, xformers/triton/__init__.py
Not much, just removing a lot of boilerplate code to conditionally load triton parts
=> [minor] Cleaning up the conditional triton loading

CHANGELOG.md
=> update for release 0.0.6

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
=> update for release v0.0.7

examples/microGPT.py, examples/microViT.py
- microViT: fix the classification token option. Improves the classification a fair bit, and that's what ViT originally suggested
- microGPT: use the settings proposed in the [original minGPT char example](https://github.com/karpathy/minGPT/blob/master/play_char.ipynb). This slows down the training (roughly 40 minutes per epoch on a laptop) but is more of a apples-to-apples comparison
=> [minor] Improve on the micro examples

examples/microGPT.py, examples/microViT.py, xformers/factory/model_factory.py
Not much, just showing in the examples how to use the reversible layers, and fixing a related bug
=> [minor] explaining how to use reversible in the examples

tests/test_ortho_attention.py, xformers/components/attention/ortho.py
Orthoformer was a sore spot in the code coverage, it exposes a few options which were not tested really. Hijacking the Nystrom unit test from @dianaml0 and repurposing it for Orthoformer, in order to sanity check it
=> [chore] Adding a unit test for orthoformer, increase code coverage

xformers/triton/utils.py
Yet another micro fix, removing dead code (used to be accessed in the triton kernels, but a triton version upgrade made this part of the core triton package)
=> [chore] Removing dead code in the triton utils

.isort.cfg, tests/test_attentions.py, xformers/components/__init__.py
Fixes #135. Probably not perfect, but that's something
=> [chore][minor] Adding some testing of different projection options

examples/build_model/my_model.py, tests/test_hydra_helper.py, xformers/factory/hydra_helper.py
Fixes failing open source requirements
=> add copyright headers

tests/test_pytorch_transformer_parity.py
=> [minor] Make sure that test parsing works on non-triton-enabled platforms

tests/test_triton_dropout.py, xformers/triton/dropout.py
Fixes #146, microGPT sampling after the training. The issue was that at that time the model and samples are on cpu, but the model has triton parts, and these are not cpu compatible 
=> [hotfix] fix #146

.circleci/config.yml, xformers/benchmarks/benchmark_vit_timm.py
- Fix the config format so that it fits the newer requirements
-  add a super small CI job to make sure that this does not happen again
Fix #148 
=> [fix] Fix the ViT benchmark being broken by a refactor  + prevent future breakages

tests/test_triton_softmax.py
removing some printouts which slipped in (but were caught by eagle-eyed @dianaml0 !)
=> [nit] Removing debug prints

HOWTO.md
these should probably be linted if possible...
=> fix remaining indentation

CHANGELOG.md, tests/test_triton_dropout.py, xformers/triton/k_dropout.py
Fixes #173, many thanks @tridao for the bug report ! Fix + add a unit test to catch that
=> Fix #173, dropout repeatibility / mishandled seeds

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
=> release 0.0.8

xformers/components/in_proj_container.py
Opportunistic, I was refactoring the projections in https://github.com/facebookresearch/xformers/pull/178 and spotted this difference. I'm not sure whether it's something which would have affected some of your tests @dianaml0 ?
Scale the weights by 1/sqrt(2) when KQV have the same dimensions, same as [fairseq](https://github.com/pytorch/fairseq/blob/cf8ff8c3c5242e6e71e8feb40de45dd699f3cc08/fairseq/modules/multihead_attention.py#L99)
=> [feat] Scale the weight init in the MHA projections when same dimensions all around

tests/ragged_inference/test_seq_kv_cache.py, tests/utils.py, xformers/helpers/test_utils.py
Adds some tests of some primitives that will be useful for making efficient ragged inference triton kernels
=> [feat] 1/N Ragged inference - Add tests

tests/ragged_inference/test_seq_kv_cache.py
Should fix the CI dying on this unit test, a little too big
cc @nottombrown  to check that this is still ok, guess is yes
=> [hotfix][ragged attention] Minor, smaller workload to fit a T4

.github/PULL_REQUEST_TEMPLATE.md
=> point to xformers files instead of fairscale

README.md
mix of vanity and north star ?
=> [minor] Adding a "Downloads" badge

tests/test_triton_dropout.py
[This CPU test](https://github.com/facebookresearch/xformers/blob/30004215a2917d7d665ecf3b4979d215989e8c27/tests/test_triton_dropout.py#L42) is currently run even if Triton is unavailable, which causes it to fail in that case. I tested with this change, and now the test is skipped if Triton is unavailable, runs in Triton is available, and all the other tests run if both Triton is available and there is a gpu.
=> [fix] Don't run cpu test if triton is unavailable

docs/source/conf.py
Fix the numpy reference having moved recently, this is used by sphinx. Main was broken for the last two commits because of that
=> [hotfix] Doc build

tests/test_triton_softmax.py, xformers/triton/softmax.py
We had a default dispatch for CPU tensors in the `triton/softmax` implementation. But it didn't handle the `causal` flag properly.
Instead, it raised a warning and returned wrong values.
Instead, let's mask the tensor with a causal mask, so that results match on both CPU and GPU.
=> Fix causal flag on softmax Triton on CPU

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
=> release 0.0.9

examples/microViT.py
- fix a bug in the LR scheduler in the microViT example (was not taking grad accumulation into account)
- better defaults (longer training + lower LR)
=> [Minor] Better microViT presets + LR scheduler bugfix

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
Release v0.0.10
- [0] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
=> [chore] v0.0.10

MANIFEST.in, setup.py
Fixes `python3 setup.py sdist` creating an archive which was missing a ton of files
=> [chore] Make sure that source files are in the pip package

requirements-test.txt
`git://` throws an error, updating to `https://`
=> Fix requirement

.circleci/config.yml, tests/test_compositional_attention.py
required for FB infra, quick follow up from https://github.com/facebookresearch/xformers/pull/241, speed up the tests on cpu and in general 
- [🙃] Did you have fun?
- [o] Did you make sure to update the docs?
- [o] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? (if needed)
=> [minor] Speeding up comp attention test on CPU 

tests/test_compositional_attention.py
Follow up from https://github.com/facebookresearch/xformers/pull/241#discussion_r831157353
=> [comp attention test][super minor 🦸] Removing the -1- cases

docs/requirements.txt
=> [fix][doc] Force a compatible jinja2 version

tests/test_attentions.py, tests/test_block_factory.py, xformers/components/in_proj_container.py, xformers/components/reversible.py
Follow up from https://github.com/facebookresearch/xformers/pull/247
+ add other unit tests 
-> unit tests should still be in the green + improved test coverage 
- [ 🙃 ] Did you have fun?
- [o] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? (if needed)
=> [minor] testing the embedding projection + couple of other low hanging fruits

tests/test_rotary_embeddings.py
Fixes this unit test being flaky on newer cuda/pytorch (related to triton 2 PR). 
The core of the unit test is to check that the rotary embeddings focus the attention by default (if the embeddings are the same) more on the close range. The unit test was flaky because this is tested by substituting the (0,0) attention result to the whole attention matrix, and some other diagonal result could be marginally bigger.
=> [minor] Rotary embedding relax unit test

CHANGELOG.md, xformers/benchmarks/benchmark_mlp.py
Add a benchmark for MLP vs FusedMLP. This should be similar to `benchmark_triton_dropout.py` since internally that is what is being used, so okay with not adding this to avoid redundancy.
=> [feat] mlp benchmark

.circleci/config.yml
=> [CI][minor] Fix typo in the /experimental ci script

examples/README.md
=> Fix img link

tests/test_triton_layernorm.py
Addresses #286, no issue really, with the current main (not the case with the latest pip package, we need to update) the triton layernorm is bfloat16 compatible. This PR adds a test to check that out 
cc @SeanNaren 
=> [ci] layernorm + bfloat16 - adding a test

xformers/components/attention/blocksparse.py
Since attention mask is no longer possible, perhaps confusing to still have these around.
=> Remove mask references in blocksparse attention

README.md
BibTeX was improperly formatted
=> [fix] Fix BibTeX

xformers/benchmarks/benchmark_blocksparse_transformers.py, xformers/benchmarks/utils.py
Benchmark Torch, Triton and Sputnik kernels for Sparse Transformers.
cc @cpuhrsch
=> [feat] Benchmarking BlockSparse Kernels for Sparse Transformers

xformers/components/in_proj_container.py
Could be something which influenced #219, in the self attention case we were not initializing the weights correctly. These depend on fan_in and fan_out, which are the weight tensor dimensions, and having merged all the weights in the case of the self attention these dimensions were not correct (too big in the case of the output). Fixing that here
Checking on Cifar this has a minor but positive impact on accuracy for a metaformer
- [ x Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
=> [fix][minor] Fixing the self attention init not respecting the q/k/v dimensions

README.md
Fixes #306. Tentatively making the README a little cleaner (collapsed sections by default) and better organized
- [-] Did you write any new necessary tests?
=> [fix] better instruction installation, tentatively easier to read

tests/test_block_factory.py, tests/test_pickling.py, xformers/triton/dropout.py
Fixes #290 I believe
- [🙃] Did you have fun?
=> [fix] Pickling issues with xformer models (#290)

CHANGELOG.md, docs/source/conf.py, xformers/__init__.py
Adjust the version referencing to move to 0.0.12.dev, tracking a 0.11 release
cc @fmassa @dianaml0 
=> [chore] Release v0.0.11, switch version to 0.0.12.dev

.pre-commit-config.yaml, requirements-test.txt, stubs/torch/fft/__init__.pyi, stubs/torch/linalg/__init__.pyi, stubs/torch/nn/functional.pyi, stubs/torch/nn/functional/__init__.pyi, stubs/torch/sparse/__init__.pyi, stubs/torch_stub_tests.py, tests/test_mem_eff_attention.py, tests/test_triton_blocksparse.py, xformers/benchmarks/LRA/run_tasks.py, xformers/benchmarks/benchmark_blocksparse_transformers.py, xformers/benchmarks/benchmark_encoder.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/benchmarks/benchmark_nystrom_utils.py, xformers/benchmarks/benchmark_pytorch_transformer.py, xformers/components/attention/attention_patterns.py, xformers/components/attention/compositional.py, xformers/components/residual.py
See https://github.com/fairinternal/xformers/pull/350 and https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
Bumping up black and reformatting accordingly
=> [CI] Bumping up black

tests/test_global_attention.py
Fixes a flaky unit test, see https://app.circleci.com/pipelines/github/facebookresearch/xformers/1709/workflows/8446fd5d-fb75-4d4b-87a0-7394ec01bdc0/jobs/3990 (unrelated to the changes in this PR)
=> [CI][minor] flaky unit test fix for global attention

xformers/benchmarks/LRA/run_tasks.py, xformers/benchmarks/utils.py, xformers/utils.py
Unused util that I saw randomly, this most probably belongs to LRA more than core xformers (it's used there). Insta land @fmassa @dianaml0, I hope that works, trying to save you some cycles  
=> [cleanup] minor, moving a util from core xformers to LRA

xformers/factory/weight_init.py, xformers/triton/dropout.py
Follow up from #312 that I landed a little too early
- removing a code snippet which was not being used
- do not recurse the init if we found a part which owned it
=> [minor] codecov fix + handle parts owning their init better

tests/test_rotary_embeddings.py
Adds several unit tests on uncovered methods in rotary.py
=> Rotary testing

tests/test_sparse_tensors.py, tests/test_triton_fused_linear.py
not checking that the grads exist at this point (they should), so mypy is technically correct even if a little narrow minded there
=> [nit] fixing mypy, broken on #333

examples/build_model/conf/stack/base_encoder.yaml
Fixes a tiny typo. No issue warranted, though this does incur an error.
=> fix tiny typo. :-)

tests/test_attentions.py
For completeness' sake, we were testing equivariance but not invariance. Credits to Francois Fleuret for the [heads up to all](https://twitter.com/francoisfleuret/status/1539622884766896128)
=> [minor][attention] Better invariance and equivariance checks

BENCHMARKS.md, xformers/triton/dropout.py
fixes minor variable assignment bug; fixed blocksparse benchmarking images
=> tiny triton dropout fix; blocksparse documentation fix

setup.py
If the user forgot to perform `git submodule update --init --recursive` in their clone, they would get cryptic errors during compilation.
Now raise errors early with an explicit message.
=> Raise early errors if submodules not available

.gitmodules, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h
We no longer need a custom cutlass fork :)
(this also updates cutlass version - which will be useful for partial tiles)
=> Revert changes to cutlass

requirements-test.txt, xformers/components/attention/core.py, xformers/ops.py
Removes functorch install that was causing failures. Will follow up with PR to fix those failures, but created this PR for now to get CircleCI green.
Also fixes some mypy errors.
=> Temporary fix for CircleCI errors

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu
=> Fix race condition when `K>128|64` in attention forward

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
Performance improvement:
**A100**
```
[------------------------------------- attention (attn_bias=<class 'NoneType'>) ------------------------------------]
|  4151847_dispatch_w_blocks  |  vanilla  |  afbcefb_update_scaling_nobounds
1 threads: ----------------------------------------------------------------------------------------------------------
f32 fwd_gen B=256, M=128, K=16     |              57.2           |    159.3  |                 56.2            
f16 fwd_gen B=256, M=128, K=16     |              32.9           |     60.8  |                 32.3            
f32 fwd_gen B=256, M=128, K=32     |              58.6           |    136.3  |                 57.5            
f16 fwd_gen B=256, M=128, K=32     |              35.0           |     63.3  |                 33.7 …
```
=> Disable bounds checks when not needed in scaling coefs

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
Taken from FlashAttention:
https://github.com/HazyResearch/flash-attention/blob/04fb198523a687f8f66e304e8555b3d62cb52a2a/csrc/flash_attn/src/fmha/softmax.h#L222-L224
=> AttentionFwd: Use exp2f instead of expf to gain ~5%

setup.py
Performance on P100/V100: https://pastebin.com/raw/XRz1mDnV
=> Compile with --use_fast_math

xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
Currently the code is split in 2 functions for the 2 matmul. Having everything in one single function will make it easier to preload in the first function what we need in the second function
**BENCHMARKS**
<details>
<summary>A100</summary>
```
[------------------------------------------- attention (attn_bias=<class 'NoneType'>) -------------------------------------------]
|  7446017_outputrf  |  0d5a385_main  |  vanilla  |  e36e413_onefunc  |  ec4ca77_pipeline
1 threads: -----------------------------------------------------------------------------------------------------------------------
f16 fwd_gen B=256, M=128, K=16     |         23.8       |       25.5     |     60.6  |         26.9      |         25.6     
f32 fwd_gen B=256, M=128, K=16     |         46.4       |       49.1     | …
```
=> AttnForward: don't split the code in multiple funcs

xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h
This PR brings a few modifications to the A100/f16 kernel that uses `MmaMultistageFromSharedMemory`.
(1) Limit the number of Mma stages if we have an upper bound on the dimension `K` (eg with blocks of size 64x64, we know that we need to load at most 64 values of `V` - it was set to 96 before). This will free some shared memory
(2) If we have space to store the entire matrix `V` in shmem, load it entirely from the beginning (asynchronously)
(3) Start loading `V` with `cp.async` (gmem->shmem) while we update the `m*`,`s*` coefs because they take a long time. This allows the second matmul to start directly.
(3) is only applied to A100. On earlier GPUs, we don't have `cp.async` and have to go through registers. Using more registers slows down the kernels
**BENCHMARKS**
<details> …
=> AttnForward: Pipelining for f16/A100

xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_access_iterator_residual_last.h, xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_iterator_residual_last.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
Unmodified code (just clang-formatted) - to make it easier to review the next PR
| PR | Title |  Merges Into  |
|:--:|:------|:-------------:|
|#391|[MMA_FROM_SMEM_IT_RES] Fix padding of LSE in forward|**N/A**|
|#392|[MMA_FROM_SMEM_IT_RES] Copy over files from cutlass|#391|
|#393|[MMA_FROM_SMEM_IT_RES] Change how residuals are handled|#392|
=> [MMA_FROM_SMEM_IT_RES] Copy over files from cutlass

xformers/__init__.py
Fixes #400 
Tested locally, should be nicer to use (does not fix cuda kernels compiles, but that's one less hiccup for stable diffusion users, among others)
- Well, that's easier than upgrading triton, that's for sure
- [[x] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
=> [fix] Survive triton v1 imports 

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu
* #443
* #442
* #440
* #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* __->__ #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
=> noinit: Don't initialize backward's gradients to zero

tests/test_mem_eff_attention.py, xformers/benchmarks/benchmark_mem_eff_attention.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
* #443
* #442
* #440
* #439
* __->__ #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
Also rename generic->cutlass for kernel name
=> cleanup: Cleanup forward/backward dispatch

xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h
* #443
* #442
* #440
* __->__ #439
* #438
* #434
* #429
* #426
* #421
* #415
* #412
* #411
* #433
* #432
* #405
* #404
* #403
* #399
* #398
* #397
* #396
* #395
**SUMMARY**
This means we can effectively remove `query_start()` function calls.
This will be useful to support arbitrary sequence lengths
<details>
<summary>A100 fw</summary>
```
[----------------------------------------- attention (attn_bias=<class 'NoneType'>) -----------------------------------------]
|  flash[flshatt]  |  37_noqs_1b917ab[cutlass]  |  3_benchmarks_a2c3089[fwd_gen]  |  vanilla 
1 threads: -------------------------------------------------------------------------------------------------------------------
f16 B=160, M=4096, …
```
=> noqs: Advance pointers to block position

.circleci/config.yml, setup.py
* #452
* #451
* #449
* #448
* #447
* #446
* #445
* __->__ #444
=> ci: Enable CI on multiple GPUs

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/mma_from_smem.h
* #452
* #451
* #449
* #448
* #447
* __->__ #446
* #445
* #444
=> fw_forceinline: Apply forceinline for all device functions

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h
* #452
* #451
* #449
* #448
* __->__ #447
* #446
* #445
* #444
=> v100reduc: Implement warp reduction on V100 for same line [5-10% improv]

xformers/components/attention/csrc/cuda/mem_eff_attention/attention_scaling_coefs_updater.h
* #452
* #451
* #449
* __->__ #448
* #447
* #446
* #445
* #444
=> log2ef: Multiply by M_LOG2E in float (rather than double)

xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/predicated_tile_access_iterator_residual_last.h
* #452
* __->__ #451
* #449
* #448
* #447
* #446
* #445
* #444
<details>
<summary>P100 fw</summary>
```
[------------------------- attention (attn_bias=<class 'NoneType'>) ------------------------]
|  42_p100nvcc2_32558cc7  |  41_packed_45babdda  |  vanilla 
1 threads: ----------------------------------------------------------------------------------
f16 B=16, M=4096, K=40     |          10619.2        |        10645.1       |   13605.3
f32 B=16, M=4096, K=40     |           9444.5        |         9355.6       |   17065.5
f16 B=16, M=16384, K=40    |         158838.8        |       159467.5       |          
f32 B=16, M=16384, K=40    |         142538.7        |       142012.7       |          
f16 B=160, M=4096, …
```
=> p100nvcc2: Better workaround for compiler bug on P100

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_forward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/gemm_kernel_utils.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_forward.h, xformers/ops.py
* #459
* #458
* #456
* __->__ #454
* #453
* #452
<details>
<summary>A100 bw</summary>
```
[------------------------------------- attention backward (attn_bias=<class 'NoneType'>) --------------------------------------]
|  45_bwpacked_e53c5f3[cutlass]  |  vanilla  |  flash[flshatt]  |  44_bwinline_cc53fcf[cutlass]
1 threads: ---------------------------------------------------------------------------------------------------------------------
f16 B=16, M=4096, K=40     |             21548.2            |   4116.5  |                  |             21279.2          
f32 B=16, M=4096, K=40     |             67624.5            |  17671.9  |                  |             67513.2          
f16 B=16, M=16384, K=40    | …
```
=> bwpacked: Support non-contiguous Q/K/V for backward

setup.py, xformers/components/attention/csrc/attention.cpp, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/components/attention/csrc/cuda/mem_eff_attention/iterators/epilogue_predicated_tile_iterator.h, xformers/components/attention/csrc/cuda/mem_eff_attention/kernel_backward.h
- https://github.com/facebookresearch/xformers/issues/437
=> Fix compiler errors on Windows

xformers/ops.py
* #467
* __->__ #461
**PERFORMANCE ON A100**
```
[---------------------------------- attention backward (attn_bias=<class 'NoneType'>) -----------------------------------]
|  flashPacked[flshatt]  |  vanilla  |  flash[flshatt]  |  48_chunk3_31735f9[cutlass]
1 threads: ---------------------------------------------------------------------------------------------------------------
f16 B=384, M=197, H=1, K=64    |           232.6        |   1813.5  |        304.7     |              391.7
f16 B=1024, M=197, H=1, K=64   |           575.5        |   4748.5  |        764.3     |              876.9
f16 B=32, M=197, H=16, K=64    |           296.3        |   2435.2  |        393.5     |              459.9
f16 B=32, M=197, …
```
=> Pack dQ/dK/dV for flash's bw

.circleci/config.yml, packaging/conda/build_conda.py
=> build conda every commit

.circleci/config.yml, packaging/conda/xformers/meta.yaml
=> conda packages to know their python dep

LICENSE
Adding the license title, assuming it was forgotten
=> Adding the license title

xformers/components/swiglu/cuda/dual_gemm_silu_identity_mul.cu, xformers/components/swiglu/cuda/gemm_fused_operand_sum.cu
* #518
* #511
* #510
* __->__ #509
* #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* #487
* #486
=> Raise if kernel not supported on device

setup.py
* #518
* __->__ #511
* #510
* #509
* #505
* #508
* #504
* #491
* #502
* #490
* #498
* #488
* #487
* #486
=> Include git hash and install date in version

xformers/ops/unbind.py
Fixes regression introduced in https://github.com/facebookresearch/xformers/commit/0428e12accab31cc3a5677b47b61ba8e7b6dfad2#r89881527
Cc @devonbrackbill @mkosecki
=> Fix PEP448 for python < 3.8

tests/test_mem_eff_attention.py, xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu, xformers/ops/memory_efficient_attention.py
Fixes #517.
Corrects check for "support" on Sm86, as this GPU has 2x less shared memory than A100
=> Fix memory-attention dispatch for Sm86

.github/workflows/wheels.yml
Also makes it run every week
cc @AbdBarho let me know if this looks good to you
=> Wheels: One artefact file per config

HOWTO.md
=> [docs] fic typo in HOWTO.md

xformers/ops/memory_efficient_attention.py
=> enable attn_bias for Triton kernel forwards

.circleci/config.yml, .coveragerc, .flake8, .gitignore, .isort.cfg, .pyre_configuration, codecov.yml, docs/requirements.txt, requirements.txt, setup.py, xformers/ops/fmha/triton.py
* #571
* #570
* #568
* #561
* #560
* __->__ #557
* #495
* #555
* #567
**BENCHMARKS**
<details>
<summary>A100 FW</summary>
```
[---------------------------------------------- attention (attn_bias=<class 'NoneType'>) ---------------------------------------------]                            
|  flash1[flshatt]  |  triton[tritonflashatt]  |   eager   |  flash2[flshatt]  |  cutlass[cutlass]
1 threads: ----------------------------------------------------------------------------------------------------------------------------
f16 B=384, M=197, H=1, K=64    |          69.9     |             91.4         |    680.0  |          73.8     |          86.7    
f16 B=1024, M=197, H=1, K=64   |         155.9     | …
```
=> Refactor3: Embed flash's PY files as xformers._flash_attn

xformers/ops/fmha/triton.py
* #571
* #570
* __->__ #568
* #561
* #560
* #557
* #495
* #555
* #567
=> TritonFlash: Enable only on Sm80

tests/test_mem_eff_attention.py, xformers/ops/fmha/__init__.py, xformers/ops/fmha/common.py, xformers/ops/fmha/flash.py, xformers/ops/fmha/small_k.py
* #571
* __->__ #570
* #568
* #561
* #560
* #557
* #495
* #555
* #567
=> Refactor7: Restore dropout

xformers/ops/fmha/__init__.py
* __->__ #571
* #570
* #568
* #561
* #560
* #557
* #495
* #555
* #567
=> Refactor8: Reapply changes from Artem

xformers/ops/fmha/__init__.py
=> Test if operator is supported when explicitely specified

setup.py
=> Windows: copy files rather than symlink

xformers/ops/fmha/cutlass.py
=> fix cutlass SUPPORTED_MAX_K

xformers/ops/fmha/__init__.py
=> memory_efficient_attention_backward: Correctly reshape output grads

tests/test_mem_eff_attention.py, xformers/ops/fmha/tensor_with_seqlen.py
=> TensorWithSeqLen: support 'megabatches'

xformers/ops/fmha/cutlass.py
Broken after https://github.com/facebookresearch/xformers/pull/578
=> Fix CI: Remove unneeded import

setup.py
=> Force CUDA when TORCH_CUDA_ARCH_LIST is set

.github/actions/setup-windows-runner/action.yml, .github/workflows/wheels.yml, .github/workflows/win-build.yml
Reduces code duplication, as a continuation of #591
After this, I will investigate possibilities of speeding up the build, not sure If I can squeeze something out...
=> Consolidate Windows Runners' Setup

setup.py
Fixes #611 
I think this issue shows us that we should prioritise this:
https://github.com/facebookresearch/xformers/blob/f351feee23a86ac0f21d1d3df067807f49029426/.github/workflows/wheels.yml#L133
=> Copy flash-attention when building wheels

.circleci/config.yml
=> conda build for PyTorch 1.13.1

packaging/build_conda.py
=> [easy] conda path fix

.github/workflows/wheels.yml
Adds 5.0+PTX to cuda archs when building wheels as per https://github.com/facebookresearch/xformers/issues/625#issuecomment-1375569435
=> Add 5.0+PTX to wheels

.circleci/config.yml, packaging/build_conda.py
=> fairinternal conda => artifacts

docs/source/xformers_mingpt.ipynb
=> [docs] fix typo in xformers_mingpt.ipynb

README.md
independant isn't correct spelling, while independent is.
Fixes typo
- [ x] Did you have fun?
=> tiny typo fix

xformers/csrc/attention/cuda/fmha/attention_backward_generic.cu
Remove useless include which is also an ATen internal file which is not meant to be inlcuded from external. 
- [x ] Did you have fun?
- [x ] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [x ] N/A
- [x ] N/A
=> Remove useless include

xformers/csrc/swiglu/swiglu_packedw.cpp, xformers/ops/swiglu_op.py
Add CUDA dispatch key for swiglu_packedw that can be used in the inference path. 
=> Add CUDA dispatch key for swiglu_packedw

xformers/csrc/attention/cuda/fmha/pytorch_utils.h
This would have saved me 30 minutes of painful debugging Alibi.
Minor DevX improvement: better error messages in `TORCH_CHECK`
=> Improve the internal check error messages

xformers/ops/fmha/flash.py
Add the direct use of flash attention v2 option (instead of building from source)
=> Add the direct use of flash attention v2 option (instead of building from source)

.github/workflows/wheels_reusable.yml
This will give us support for cuda 12.1, and it will be possible to install xformers using the same index URL as pytorch
=> [ci] Uploading wheels to pytorch.org

.github/workflows/wheels_reusable.yml
TODO: Only for proper releases
=> [ci/pytorch] Fix upload path + set public ACL

.github/workflows/wheels_reusable.yml
=> [ci] Disable Flash-Attention build on CI for windows, as we timeout

README.md, packaging/compute_wheel_version.py
(will merge once we have proper cuda 12 builds + upload to pytorch is done)
Builds are listed there:
https://download.pytorch.org/whl/cu121/xformers/
https://download.pytorch.org/whl/cu118/xformers/
=> Update install instructions + fix linter

README.md
Fixes #909
There is a typo in the README.md
- [] N/A
=> fix: fixed typo in README.md

README.md
updated docs. there were some typos in that.
=> fixed multiple typos in readme.

xformers/ops/fmha/__init__.py
=> #922: Fix incorrect transpose operations in equivalent PyTorch code for memory_efficient_attention in documentation.

xformers/csrc/attention/hip_fmha/ck_attention_forward_decoder.h, xformers/csrc/attention/hip_fmha/ck_attention_forward_decoder_splitk.h
Maybe fixes fbcode cpp extension build error
`# pytest -rpfs /xformers/tests/test_mem_eff_attention.py -k decoder`
cc @jianyuh
=> fix includes in decoder and splitk decoder

HOWTO.md
=> Remove unused import in example HOWTO.md

.github/workflows/wheels.yml, .github/workflows/wheels_build.yml
Fixes build timeouts for rocm wheels
=> [ROCm] tweak rocm wheel build workflow to avoid ci timeouts

xformers/ops/fmha/ck.py
Some Change to the xformers/ops/fmha/ck.py so that correct seqstart_k and seqlen_k can be passed to the C++ codes for 
- BlockDiagonalGappyKeysMask
- BlockDiagonalPaddedKey
And their derived attn-bias types.   
The change has passed all tests in 
```bash
pytest tests/test_mem_eff_attention.py::test_forward -k "not triton"  -k "not flshattF"  -k "not fa2F"
```
=> Enable complete BlockDiagonalGappyKeysMask and BlockDiagonalPaddedKey Support on CK

docs/source/xformers_mingpt.ipynb
Small PR - updates the xFormers MinGPT Colab notebook reference.
=> Update xFormers MinGPT notebook reference

.github/actions/setup-build-cuda/action.yml, .github/selective_ci/selective_ci.py, .github/workflows/rocm_build.yml, .github/workflows/wheels.yml, .github/workflows/wheels_build.yml, .github/workflows/win-build.yml, CHANGELOG.md, README.md, requirements.txt, xformers/components/attention/core.py
Taking over changes from https://github.com/facebookresearch/xformers/pull/1202 to land in xFormers to support PT 2.6.0
=> Build with PyTorch 2.6.0, update CUDA targets

.github/workflows/wheels.yml
Fixes https://github.com/facebookresearch/xformers/issues/1215
=> Fix missing release for CUDA 12.6 on Windows

tests/test_mem_eff_attention.py
=> Make dtype test generation deterministic

tests/test_mem_eff_attention.py
=> Fix shape variable overriding in test case generation logic

xformers/csrc/sparse24/sparse24_gemm_sm90.cu
Fixes [#1231](https://github.com/facebookresearch/xformers/issues/1231).
Allows builds for the RTX 5000 series.
=> Fixed RTX 5090 build issue
